### ISSUE TITLE
Submitting new issues

### ISSUE THREAD

**Issue by alex-swiftify** [Swiftify-Corp/Swiftify#1]
You are welcome to post any issues related to the Objective-C to Swift Converter here.

Please be sure to include your original (Objective-C) code sample, as well as both "actual" and "expected" Swift results.

**Comment by KvanTTT** [comment]
I recommend using [Issue and pull request templates](https://blog.github.com/2016-02-17-issue-and-pull-request-templates) instead :)

**Comment by alex-swiftify** [comment]
Great idea - will take a look - thanks! :)
