### ISSUE TITLE
[NSArray indexOfObjectPassingTest:] doesn't exist in Swift

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#102]
http://swiftify.me/mxblxz

**Comment by tomattoz** [comment]
Here we can translate declarations @[] -> NSArray and @{} -> NSDictionary, and then all rules of these type should be applied.
In this case next rule should be applied:
NSArray.indexOfObjectPassingTest:={receiver:NSArray?}.indexOfObject(passingTest: {0:(Any, Int, UnsafeMutablePointer<ObjCBool>) -> Bool}) -> Int

**Comment by tomattoz** [comment]
Issue: https://swiftify.atlassian.net/browse/SWC-1050

**Comment by alex-swiftify** [comment]
Fixed (will be available since the next update).
Converter output:
```
([] as NSArray).indexOfObject(passingTest: { obj, idx, stop in
    return true
})
```
