### ISSUE TITLE
Method call containing ternary operator that returns nil is wrapped with if let

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#105]
http://swiftify.me/0iutnq/1

**Comment by tomattoz** [comment]
Issue: https://swiftify.atlassian.net/browse/SWC-1051

**Comment by alex-swiftify** [comment]
@nickasd , @tomattoz Fixed.
Changes made:
* Translate XCTAssert macro to XCTAssert()
* Use an `??` operator instead of `if let` when unwrapping interpolated string arguments.

Converter output:
```
XCTAssert(true, "\((true ? "" : nil) ?? "")")
```
