### ISSUE TITLE
IBActions should use _ for one and only parameter label

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#107]
For example, `- (IBAction)openInFinder:(id)sender` currently results in `@IBAction func open(inFinder sender: Any)`, but the `sender` argument will rarely be mentioned in the method name.
http://swiftify.me/uo7ql6

**Comment by tomattoz** [comment]
@nickasd not sure if I understand what do you mean.
We just use argument name from objc code, see example https://swiftify.com/converter/code/uo7ql6/1

**Comment by nickasd** [comment]
I'm not sure anymore what I meant either. Perhaps it's that it's not common to have `IBAction` with parameter labels (`inFinder` in this case), so it should be `@IBAction func openInFinder(_ sender: Any)` (which is what Xcode creates by default as well), or at least `openInFinder(sender: Any)`, since having the label `inFinder` for a parameter named `sender` makes no sense.

**Comment by tomattoz** [comment]
Ok, I think current translation is good enough, at least I can't see any side effects. So closing this out.
