### ISSUE TITLE
Assuming the current class as the receiver of selectors is wrong

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#11]
http://swiftify.me/lhkhct

**Comment by alex-swiftify** [comment]
Fixed (will be available after the next update).
The class qualifier (`FileManager`) is inferred from the method mappings we have for the specified selector, if available.

Converter output:
```
class asd: NSWindowController {
    func asd() {
        FileManager.instancesRespond(to: #selector(FileManager.trashItem(at:resultingItemURL:)))
    }
}
```
