### ISSUE TITLE
[NSURL stringByDeletingPathExtension] creates 2 nested URL instances

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#110]
http://swiftify.me/as38zd

**Comment by tomattoz** [comment]
@nickasd, you initial code is wrong.

Objc (initial, "stringByDeletingPathExtension" is member of NSString, not NSURL):
[NSURL fileURLWithPath:@"/Users/me/asd.txt"].stringByDeletingPathExtension;

Objc (right):
@"/Users/me/asd.txt".stringByDeletingPathExtension;

Swift:
URL(fileURLWithPath: "/Users/me/asd.txt").deletingPathExtension().absoluteString
