### ISSUE TITLE
[[NSURL lastPathComponent] stringByDeletingPathExtension] creates wrong string

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#111]
This sequence of methods would transform the string `/Users/me/asd.txt` to `asd` in Objective-C, but the converter creates the code `URL(fileURLWithPath: URL(fileURLWithPath: "/Users/me/asd.txt").lastPathComponent ?? "").deletingPathExtension().absoluteString`, which for a sandboxed app results in `/Users/me/Library/Containers/org.example.app/Data/asd`. Probably, the converter should first invoke `stringByDeletingPathExtension` and then `lastPathComponent`, which produces the correct string.
http://swiftify.me/5r5f53

**Comment by nickasd** [comment]
Also see this degenerated example:
http://swiftify.me/i77u5b

**Comment by alex-swiftify** [comment]
Fixed by resorting to using NSString function.
Converter output:
```
(URL(fileURLWithPath: "/Users/me/asd.txt").lastPathComponent as NSString).deletingPathExtension
```
