### ISSUE TITLE
Variable with same name as method

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#114]
Causes error `Cannot call value of non-function type`.
http://swiftify.me/h7jr9h

**Comment by alex-swiftify** [comment]
@nickasd While we have just fixed a related issue: https://swiftify.atlassian.net/browse/SWC-987
in your particular sample, the converter explicitly uses a `self.` prefix to avoid the ambiguity.

The following compiles just fine in Xcode:
```
import Foundation

class Test {
    func test() {
        let asd: Any? = nil
        self.asd(asd)
    }
    
    func asd(_ asd: Any?) {
    }
}
```
https://share.getcloudapp.com/YEuvobGB

**Comment by alex-swiftify** [comment]
P.S. See https://github.com/Swiftify-Corp/Swiftify/issues/54 for a related case that has been fixed indeed.
