### ISSUE TITLE
Error variable should be discarded when catch block is generated

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#117]
http://swiftify.me/iqz8i4

**Comment by tomattoz** [comment]
Issue: https://swiftify.atlassian.net/browse/SWC-1053

**Comment by alex-swiftify** [comment]
Fixed, along with these issues:
* https://swiftify.atlassian.net/browse/SWC-659
* https://swiftify.atlassian.net/browse/SWC-1053
* https://github.com/Swiftify-Corp/Swiftify/issues/117

Converter output: 
```
do {
    try FileManager.default.createDirectory(at: nil, withIntermediateDirectories: true, attributes: nil)
} catch {
    print("\(error?.localizedDescription ?? "")")
}
```
