### ISSUE TITLE
Catch block is empty if throwing expression is immediately followed by another expression

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#118]
http://swiftify.me/p700bf

**Comment by tomattoz** [comment]
It looks like the second "if" now translates pretty well.
But the first contains three errors:
- https://swiftify.atlassian.net/browse/SWC-1054
- https://swiftify.atlassian.net/browse/SWC-1055
- https://swiftify.atlassian.net/browse/SWC-1056

**Comment by alex-swiftify** [comment]
Solved the issue with missing negation in the output (in https://swiftify.atlassian.net/browse/SWC-1055).
A complete solution would be the code mentioned in a comment [here](https://swiftify.atlassian.net/browse/SWC-1055?focusedCommentId=42733) which requires reimplementing our current approach to support binary expressions with negations and nesting of any level. The complete solution is postponed to https://swiftify.atlassian.net/browse/SWC-1190.
