### ISSUE TITLE
NSView.autoresizingMask

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#12]
Instead of `view.autoresizingMask = UIView.AutoresizingMask(rawValue: NSView.AutoresizingMask.minYMargin.rawValue)` you should do `view.autoresizingMask = .minYMargin`.
http://swiftify.me/pd32ll/2

**Comment by tomattoz** [comment]
This happens because of unknown view type:
http://swiftify.me/pd32ll/3
