### ISSUE TITLE
Overriding setter could use didSet

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#122]
When the first line of an overridden setter is the super call, instead of overriding both `get` and `set` you could just convert it to a `didSet`.
http://swiftify.me/rhg1q1

Similarly, but possibly not something that everyone would want, if the super call is somewhere in the middle of the overridden setter, you could also generate a `willSet`.

**Comment by alex-swiftify** [comment]
Related JIRA issue:
https://swiftify.atlassian.net/browse/SWC-874

**Comment by alex-swiftify** [comment]
@nickasd Since this is finally in progress, I wanted your advice on whether the pattern from #178 (see [this comment](https://github.com/Swiftify-Corp/Swiftify/issues/178#issuecomment-1624000938)) should be also converted to a didSet accessor.
Thanks in advance!

**Comment by alex-swiftify** [comment]
Fixed the case from the summary (overridden property setter should use `didSet`).

Only support for `didSet` is implemented, support for `willSet` is postponed until more feedback is received.

```
class TextFieldCell: NSTextFieldCell {
    override var backgroundStyle: NSView.BackgroundStyle {
        didSet {
            textColor = backgroundStyle == .dark ? NSColor.alternateSelectedControlTextColor : NSColor.alternateSelectedControlColor
        }
    }
}
```
