### ISSUE TITLE
Optional is not unwrapped

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#124]
http://swiftify.me/gd012d

**Comment by tomattoz** [comment]
Fixed this way:

        let bla: [AnyHashable]? = []
        let indexes: NSIndexSet? = nil
        var asd: [AnyHashable]? = nil
        if let indexes = indexes {
            asd = bla?.enumerated().filter { indexes.contains($0.offset) }.map { $0.element }
        }
