### ISSUE TITLE
return statement in constructor is lost

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#126]
In this example, it means that the constructor always returns `nil`.
http://swiftify.me/kx9yzv

**Comment by tomattoz** [comment]
Issue: https://swiftify.atlassian.net/browse/SWC-1059

**Comment by alex-swiftify** [comment]
Fixed. Converter output:
```
class Asd: NSTextAttachment {
    required init?(pasteboardPropertyList propertyList: Any, ofType type: NSPasteboard.PasteboardType) {
        if true {
            return super.init(data: nil, ofType: nil)
        }
        return nil
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
}
```

**Comment by alex-swiftify** [comment]
@nickasd Upon reviewing related cases, I found that the return statement was removed because `nil` [is the only return value permitted in an initializer](https://take.ms/w45Sx).

Hence it appears that we need to keep the `return` statement, but we cannot actually return a value, resulting in the following output:

```
class Asd: NSTextAttachment {
    required init?(pasteboardPropertyList propertyList: Any, ofType type: NSPasteboard.PasteboardType) {
        if true {
            super.init(data: nil, ofType: nil)
            return
        }
        return nil
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
}
```

I know it's been a long time since this was posted, but I'd appreciate your feedback here.

**Comment by nickasd** [comment]
I guess that when returning a super call inside a branch, simply keeping the super call and putting the return on the next line is fine.

**Comment by alex-swiftify** [comment]
@nickasd Thanks, already implemented this way. 
However, here is another case when this logic does not play well https://swiftify.atlassian.net/plugins/servlet/mobile?originPath=%2Fbrowse%2FSWC-1194#issue/SWC-1194
Feel free to suggest how would you handle that case.

**Comment by nickasd** [comment]
If the method returns something else than a super call, then making it a class method seems a good solution I wouldn‘t have thought of. Otherwise, I would be fine with having a compiler error that requires my attention.

**Comment by alex-swiftify** [comment]
@nickasd Thanks for commenting, I'll try implementing https://swiftify.atlassian.net/browse/SWC-1194 as suggested.
