### ISSUE TITLE
Issue with conversion of String.

### ISSUE THREAD

**Issue by Ibrahimhass** [Swiftify-Corp/Swiftify#128]
I tried the following code snippet from [StackOverflow](https://stackoverflow.com/a/30123907/5807290). The converter is not able to convert NSString to String in the above code snippet. It would be great if the devs could look into this bug. Here is the link to the [code snippet](http://swiftify.me/0oy8yx).

**Comment by alex-swiftify** [comment]
@Ibrahimhass The Objective-C code sample is missing `;` at the end of the first `NSString` variable declaration, and won't compile in Xcode either.
If you add the missing semicolon, this seems to get translated just fine: http://swiftify.me/0oy8yx/1

While I agree that would be "nice" to warn the user about such issues, I recall this is not something straightforward to fix.
Just found that we already have this logged as https://swiftify.atlassian.net/browse/SWC-810, so I'm closing this out and adding your case there.
