### ISSUE TITLE
Minor Issue with conversion UIAlertView

### ISSUE THREAD

**Issue by Ibrahimhass** [Swiftify-Corp/Swiftify#129]
**Original Objective-C Code**

    UIAlertView *alert = [[UIAlertView alloc] initWithTitle:kLocaleAppName
    message:kLocaleParkingsDetailExtendedParkingError
    delegate:self
    cancelButtonTitle:kLocaleOkButton
    otherButtonTitles:nil];
    [alert show];
**Converted Swift Code**

      let alert = UIAlertView(title: kLocaleAppName,
      message: kLocaleParkingsDetailExtendedPoiError,
      delegate: self,
      cancelButtonTitle: kLocaleOkButton,
      otherButtonTitles: "")
      alert?.show()
**Correct Swift Code**

      let alert = UIAlertView(title: kLocaleAppName,
      message: kLocaleParkingsDetailExtendedPoiError,
      delegate: self,
      cancelButtonTitle: kLocaleOkButton,
      otherButtonTitles: "")
      alert.show()

This is a minor issue but it occurs multiple times in a project. So it would be great if this could be fixed.
Thanks :)

**Comment by alex-swiftify** [comment]
@Ibrahimhass Fixed the case with this method, but still, need to ensure it does not occur with other similar initializers methods.
