### ISSUE TITLE
Update Initializers for MKCoordinateRegion and MKCoordinateSpan to match the latest syntax

### ISSUE THREAD

**Issue by Ibrahimhass** [Swiftify-Corp/Swiftify#130]
**Original Objective-C code**

`[self.mapView setRegion:MKCoordinateRegionMake(_mapView.userLocation.coordinate, MKCoordinateSpanMake(0.005136,0.005136)) animated:YES] ;`

**Converted Swift Code**
`mapView?.setRegion(MKCoordinateRegionMake(mapView.userLocation.coordinate, MKCoordinateSpanMake(0.005136, 0.005136)), animated: true) `

**Swift Code with Latest Syntax**
`mapView.setRegion(MKCoordinateRegion.init(center: mapView.userLocation.coordinate, span: MKCoordinateSpan.init(latitudeDelta:0.005136 , longitudeDelta: 0.005136)), animated: true)`

In general the **Make** keyword from API Names is in general not used any more. So while at if those could also be fixed it would be a great update

**Comment by tomattoz** [comment]
Done!
