### ISSUE TITLE
Completely nonsensical pointer conversion

### ISSUE THREAD

**Issue by kiler129** [Swiftify-Corp/Swiftify#132]
COnsider the following code:

```
#import <Foundation/Foundation.h>
#import <CoreFoundation/CoreFoundation.h>
#import <CoreAudio/CoreAudio.h>

void foo() {
    AudioValueTranslation pluginAVT;
        
    CFStringRef inBundleRef = CFSTR("com.apple.audio.CoreAudio");
    AudioObjectID pluginID;
    
    pluginAVT.mInputData = &inBundleRef;
    pluginAVT.mInputDataSize = sizeof(inBundleRef);
    pluginAVT.mOutputData = &pluginID;
    pluginAVT.mOutputDataSize = sizeof(pluginID);
}
```

The generated output is:
```
//  Converted to Swift 5.1 by Swiftify v5.1.33915 - https://objectivec2swift.com/
import CoreAudio
import CoreFoundation
import Foundation

func foo() {
    let pluginAVT: AudioValueTranslation

    var inBundleRef = "com.apple.audio.CoreAudio"
    var pluginID: AudioObjectID

    if let inBundleRef = inBundleRef {
        pluginAVT.mInputData = inBundleRef
    }
    pluginAVT.mInputDataSize = UInt32(MemoryLayout<inBundleRef?>.size)
    pluginAVT.mOutputData = pluginID ?? 0
    pluginAVT.mOutputDataSize = UInt32(MemoryLayout<pluginID>.size)
}
```

The assignment of `pluginAVT.mInputData` makes zero sense and the `MemoryLayout<inBundleRef?>.size` is even weirder :)

**Comment by alex-swiftify** [comment]
Thanks, @kiler129 for reporting!
I'll review. If you've managed to contribute a "correct" translation for your sample, feel free to share as it might be helpful.

**Comment by alex-swiftify** [comment]
@kiler129 
We've made the following changes to address your comments:

- [Convert `sizeof(value)` to `MemoryLayout.size(ofValue: value)`](https://swiftify.atlassian.net/browse/SWC-248)
- Support conversion from string and primitive types to all kinds of unsafe pointer types
- Map  `AudioObjectID` type to `UInt32` in Swift

Now the output looks like follows:
```
func foo() {
    let pluginAVT: AudioValueTranslation

    var inBundleRef = "com.apple.audio.CoreAudio"
    var pluginID: UInt32

    pluginAVT.mInputData = UnsafeMutableRawPointer(mutating: inBundleRef)
    pluginAVT.mInputDataSize = UInt32(MemoryLayout.size(ofValue: inBundleRef))
    pluginAVT.mOutputData = UnsafeMutableRawPointer(mutating: &pluginID)
    pluginAVT.mOutputDataSize = UInt32(MemoryLayout.size(ofValue: pluginID))
}
```

I hope that works. Let me know if you have more suggestions.

**Comment by kiler129** [comment]
@alex-swiftify Not quite actually. (it's 3AM so take what I say with a grain of salt)

What I found is `CFSTR()` macro cannot be simply converted to a native Swift `String` type since in fact it will have a different size. After bunch of segfaults and `what` & `siz!` returned by Core Audio I think I know how the proper conversion should look.

So keeping the original syntax when converted to Swift it will look similar to the following:
```swift
func foo() {
var pluginAVT:AudioValueTranslation //This in fact must be a var, see later example

    var inBundleRef:CFString = "com.apple.audio.CoreAudio" as CFString //Crucial to be CFString
    var pluginId: AudioObjectID


    pluginAVT.mInputData = UnsafeMutableRawPointer(mutating: &inBundleRef);
    pluginAVT.mInputDataSize = UInt32(MemoryLayout.size(ofValue: inBundleRef));
    pluginAVT.mOutputData = UnsafeMutableRawPointer(mutating: &pluginId);
    pluginAVT.mOutputDataSize = UInt32(MemoryLayout<AudioObjectID>.size);
}
```

...and since I'm sure someone will stumble across this comment looking for `kAudioHardwarePropertyPlugInForBundleID` which is almost absent from Google this would be a working example of what e.g. [Google does in Chromium](https://chromium.googlesource.com/chromium/src/+/9df2d09c9b836494e8f83a2a7657ba2a9408a23b/media/audio/mac/aggregate_device_manager.cc#135):

```swift
func getCoreAudioPluginId() -> AudioObjectID? {
    var pluginId: AudioObjectID = 0
    var inBundleRef:CFString = "com.apple.audio.CoreAudio" as CFString

    var pluginAVT:AudioValueTranslation = AudioValueTranslation(
        mInputData: UnsafeMutablePointer(mutating: &inBundleRef),
        mInputDataSize: UInt32(MemoryLayout.size(ofValue: inBundleRef)),
        mOutputData: UnsafeMutableRawPointer(mutating: &pluginId),
        mOutputDataSize: UInt32(MemoryLayout<AudioObjectID>.size)
    )
    var pluginAVTsize = UInt32(MemoryLayout.size(ofValue: pluginAVT))

    var address:AudioObjectPropertyAddress = AudioObjectPropertyAddress(
        mSelector:AudioObjectPropertySelector(kAudioHardwarePropertyPlugInForBundleID),
        mScope:AudioObjectPropertyScope(kAudioObjectPropertyScopeGlobal),
        mElement:AudioObjectPropertyElement(kAudioObjectPropertyElementMaster)
    )

    let pluginGetResult:OSStatus = AudioObjectGetPropertyData(
        AudioObjectID(kAudioObjectSystemObject),
        &address,
        0,
        nil,
        &pluginAVTsize,
        &pluginAVT
    );
    if pluginGetResult != 0 {
        print("kAudioHardwarePropertyPlugInForBundleID for com.apple.audio.CoreAudio failed")
        return nil
    }
    
    return pluginId
}
```

**Comment by alex-swiftify** [comment]
Thanks, @kiler129 for clarifications.

I'll line up the following changes:
1. Keep `AudioObjectID ` type instead of converting it to `UInt32 `.
2. Keep `CFString` type
3. Keep `var` for `pluginAVT` since its fields are assigned.

Question: is this still fine?
`pluginAVT.mOutputDataSize = UInt32(MemoryLayout.size(ofValue: pluginID))`

At least, converting to something like this could be problematic in the generic case:
`pluginAVT.mOutputDataSize = UInt32(MemoryLayout<AudioObjectID>.size);`

**Comment by alex-swiftify** [comment]
P.S. Made all changes except for keeping `var` declaration for `pluginAVT ` variable (which is postponed to [SWC-362](https://swiftify.atlassian.net/browse/SWC-362)).
