### ISSUE TITLE
if(self = [super init]) turns into super.init() != nil

### ISSUE THREAD

**Issue by bobergj** [Swiftify-Corp/Swiftify#135]
```
@interface Test : NSObject
@end

@implementation Test
- (id)init
{
    if(self = [super init]) {
    
    }
    return self;
}
@end
```

```
class Test: NSObject {
    override init() {
        super.init() != nil
    }
}
```

https://objectivec2swift.com/#/converter/code/vensus/

I would expect it to turn into just ``super.init()``
For two reasons:
1. The super class is NSObject, which has no failable initializer
2. Testing the return value of a super class initializer is not even a thing in Swift. That is done automagically.

For example:
```
class TestA {
   init?() { return nil }
}

class TestB : TestA {
   override init?() {
      super.init()
      print("after parent super")
   }
}
```
In this case, "after parent super" is never printed.

**Comment by alex-swiftify** [comment]
Fixed (will be available in the next update).
Converter output:
```
class Test {
    init() {
        super.init()
    }
}
```
