### ISSUE TITLE
NSMutableArray becomes [AnyHashable] instead of [Any]

### ISSUE THREAD

**Issue by bobergj** [Swiftify-Corp/Swiftify#136]
```
@interface Test
@property (nonatomic, strong) NSMutableArray *test;
@end
```

```
class Test {
    var test: [AnyHashable]?
}
```

http://swiftify.me/91xxqu

I would have expected ``[Any]``, but perhaps there is a good reason?

**Comment by tomattoz** [comment]
Hi! Thanks for good question.
The main reason of using AnyHashable instead of Any is support of == and != operators.
And it looks safe, because all objc types conforms to AnyHashable.
