### ISSUE TITLE
Convert to latest Swift version code

### ISSUE THREAD

**Issue by Ibrahimhass** [Swiftify-Corp/Swiftify#139]
The following swift code:
`NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)`
can be ported to the newer Swift format:
`FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).map({$0.absoluteString})
`
It would be a good to have.
https://objectivec2swift.com/#/converter/code/aabxjt/

**Comment by tomattoz** [comment]
Good improvement!
Just small change:

FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).map({$0.absoluteString})
->
FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).map({$0.path})

... to match result of NSSearchPathForDirectoriesInDomains.
