### ISSUE TITLE
Issue with inferring type of CGPoint

### ISSUE THREAD

**Issue by Ibrahimhass** [Swiftify-Corp/Swiftify#141]
**Objective-C Code**

`CGPoint scaleOrigin = (CGPoint){CGRectGetMidX(originFrame), CGRectGetMinY(originFrame)};
`
**Converted Swift Code**
`let scaleOrigin = [originFrame.midX, originFrame.minY]`

[http://swiftify.me/2mslqf](http://swiftify.me/2mslqf)
Here the result is inferred to be an array.

The correct conversion should be:
`let scaledOrigin = CGPoint.init(x: originFrame.midX, y: originFrame.minY)`

**Comment by alex-swiftify** [comment]
This has been recently reported in https://github.com/Swiftify-Corp/Swiftify/issues/134
and we have a JIRA issue where I have collected both cases: https://swiftify.atlassian.net/browse/SWC-1010.

Closing this as a duplicate to #134.

**Comment by alex-swiftify** [comment]
Also, note that this is converted properly if you explicitly specify field names like follows:
http://swiftify.me/1i7paz
