### ISSUE TITLE
Cast to CGFloat for floorf operation

### ISSUE THREAD

**Issue by Ibrahimhass** [Swiftify-Corp/Swiftify#142]
**Objective-C Code**

`CGFloat newWidth = floorf(cropBoxFrame.size.height * (aspectRatio.width/aspectRatio.height));`

**Converted Swift Code**
`let newWidth = floorf(cropBoxFrame.size.height * (aspectRatio.width / aspectRatio.height))`

[http://swiftify.me/gs9tio](http://swiftify.me/gs9tio)

The correct conversion should be:
`let newWidth = CGFloat(floorf(Float(cropBoxFrame.size.height * (aspectRatio.width / aspectRatio.height))))`

**Comment by alex-swiftify** [comment]
Fixed the parameter and return types of the `floorf` function.

To have the inner parameters being explicitly cast to `Float`, need to include the declaration of `cropBoxFrame `.

Input:
```
    CGRect cropBoxFrame;
    CGFloat newWidth = floorf(cropBoxFrame.size.height * (aspectRatio.width/aspectRatio.height));
```

Output:
```
    let cropBoxFrame: CGRect
    let newWidth = CGFloat(floorf(Float(cropBoxFrame.size.height * (aspectRatio.width / aspectRatio.height))))
```
