### ISSUE TITLE
dispatch_once_t

### ISSUE THREAD

**Issue by Styrmist** [Swiftify-Corp/Swiftify#144]
in my case you provide such comment string instead of replacement dispatch_once_t:

>  // TODO: [Swiftify] ensure that the code below is executed only once (`dispatch_once()` is deprecated)

but for me, this was the main goal, so I had to look for a solution.

I found out that in Swift all static and global variables are lazily initialized using dispatch_once, so to convert something like 

```
- (NSString)codeMap
{
    static NSString *result = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        //some code
        result = ...
    });
    return result;
}
```

you can provide

```
static let codeMap: String = {
        var result: String = ""
        //some code
        result = ...
        return result
    }()
```

this will be the clothest implementation for dispatch_once_t  in a Swift way.
The lazy initializer for a global variable (also for static members of structs and enums) is run the first time that global is accessed, and is launched as dispatch_once to make sure that the initialization is atomic. This enables a cool way to use dispatch_once in your code: just declare a global variable with an initializer and mark it private.

**Comment by alex-swiftify** [comment]
Hey @Styrmist ,

In fact, your suggestion have been already implemented.
As I see, this only works if the `result` variable gets assigned inside the `dispatch_once` block:
http://swiftify.me/ts32n5
I have just changed `...` to `@"Test";` to ensure that the source code is complete.

The output that you see is a fallback used when the converter cannot detect the pattern (in your case, the `result` variable is not being assigned, or, in your case, the input code is incomplete).

If your original code, without simplification, is not being picked by our converter, please share a more complete sample.

**Comment by Styrmist** [comment]
that is the whole block of my code:
```
- (NSDictionary<NSString *, NSString *> *)callingCodesToCountryCodeMap
{
    static NSDictionary<NSString *, NSString *> *result = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        NSMutableDictionary *map = [NSMutableDictionary new];
        for (NSString *countryCode in [PhoneNumberUtil countryCodesForSearchTerm:nil]) {
            NSString *callingCode = [PhoneNumberUtil callingCodeFromCountryCode:countryCode];
            map[callingCode] = countryCode;
        }
        result = [map copy];
    });
    return result;
}
```

**Comment by alex-swiftify** [comment]
@Styrmist  I got you, thanks!
The following works: http://swiftify.me/irioer

We'll make changes to ensure that your complete sample is processed properly.

**Comment by alex-swiftify** [comment]
@Styrmist Fixed (will be available in the next update).
Converter output: 
`class Test {
    static let callingCodesToCountryCodeMapResult: [String : String]? = {
        for countryCode in PhoneNumberUtil.countryCodes(forSearchTerm: nil) {
            let callingCode = PhoneNumberUtil.callingCode(fromCountryCode: countryCode)
            map[callingCode] = countryCode
        }
        var result = map
        map[callingCode] = countryCode
        return result
    }()

    func callingCodesToCountryCodeMap() -> [String : String]? {
        // `dispatch_once()` call was converted to a static variable initializer
        return Test.callingCodesToCountryCodeMapResult
    }
}`
