### ISSUE TITLE
Convert if statement with nil check to if let

### ISSUE THREAD

**Issue by bobergj** [Swiftify-Corp/Swiftify#145]
Instead of converting:
```
if (self.node) {
   [self.node someFunction];
}
```
to:
```
if node != nil {
     node?.someFunction()
}
```
do instead:
```
if let node = node {
    node.someFunction()
}
```

This would save us a lot of time.

Complete example:
http://swiftify.me/vpzexz

**Comment by alex-swiftify** [comment]
@bobergj Thanks for reporting!
This was in our backlog for really long.
We will take care of this in the nearest time for sure!

**Comment by alex-swiftify** [comment]
JIRA ticket: https://swiftify.atlassian.net/browse/SWC-770

**Comment by alex-swiftify** [comment]
Done (will be live since the next website update).

Converter output:
```
class Foo {
    var node: Node?

    func bundleDisplayBehaviour() -> Int {
        if let node = node {
            return node.someFunction()
        } else {
            return 0
        }
    }
}
```
