### ISSUE TITLE
Converting Objective-C code with API Availability 

### ISSUE THREAD

**Issue by Ibrahimhass** [Swiftify-Corp/Swiftify#146]
The following code snippet is not properly converted:

**Objective-C Code:**

```
@interface MyViewController : UIViewController
- (void) newMethod API_AVAILABLE(ios(11), macosx(10.13)) {}
@end

```

**Expected Swift Code:**

```
class MyViewController: UIViewController {
@available(iOS 11, macOS 10.13, *)
func newMethod() {}
}
```

**Current Converter Result:**
```
//  Converted to Swift 5.2 by Swiftify v5.2.13501 - https://swiftify.com/
func API_AVAILABLE(ios) {
}

class MyViewController: UIViewController {
    func newMethod() {
    }
}
```

[Converted Code](http://swiftify.me/p6zuze)
[Further Reading (Apple Docs)](https://developer.apple.com/documentation/swift/objective-c_and_c_code_customization/marking_api_availability_in_objective-c)

**Comment by alex-swiftify** [comment]
Thanks for reporting!
We have this in JIRA: https://swiftify.atlassian.net/browse/SWC-852 so I am closing this one as a duplicate.
