### ISSUE TITLE
Tab indenting

### ISSUE THREAD

**Issue by arlomedia** [Swiftify-Corp/Swiftify#148]
Is there an option to indent code with tabs instead of spaces? I find it a lot harder to select and edit text cleanly when it is indented with spaces.

I imagine this could be a setting in the Swiftify preferences if it doesn't already exist (I looked and didn't see one). Or maybe you can read the indent preferences from Xcode. But I think the best approach would be to use whatever the original file uses. Then the developer doesn't have to worry about it and the new file is set up as they would expect.

Currently I'm converting a few files at a time with the Advanced Project Converter, and after each batch I have to do a global search-and-replace in Xcode, and I have to run that a few times to get all the spaces. These are some extra steps I'd like to remove from my workflow.

**Comment by alex-swiftify** [comment]
@arlomedia Just checked - it seems possible to add a configurable option to change this.
I'll line this up to be included in the next versions.

**Comment by alex-swiftify** [comment]
Implemented in the converter.
Waiting for adding an option to the GUI.

**Comment by arlomedia** [comment]
Excellent. Handling this with search-and-replace in Xcode can be surprisingly slow, so this will be a nice time-saver.

**Comment by alex-swiftify** [comment]
Scheduled in Jira (private issue): https://swiftify.atlassian.net/browse/SWE-542
You will see it within one of the next app updates.
