### ISSUE TITLE
Ghost file added to WatchKit app, breaks build

### ISSUE THREAD

**Issue by arlomedia** [Swiftify-Corp/Swiftify#149]
My app has a WatchKit extension that's also in Objective-C. I haven't started converting that and am focused on converting the iOS app. I'm using the Advanced Project Converter and doing a few files at a time.

Every time I run the converter, the next build fails with this error:

`Build input file cannot be found: '/path/to/project/HeaderPrefix.swift' (in target 'MyProject Watch Extension' from project 'MyProject')`

Then I look in the Project Navigator tab (the file and folder list) in Xcode and a see a file reference named HeaderPrefix.swift, but it's red indicating there is no actual file. If I delete the reference, then the build succeeds. The cycle continues on the next conversion.

It seems like Swiftify is trying to do something with the WatchKit app, but isn't finishing and is leaving this empty file reference. I might understand this more when I start working on the Watch app code. Let me know if I can provide more info in the meantime.

**Comment by alex-swiftify** [comment]
Thanks, @arlomedia for reporting!

I have recently noticed a similar issue and this will be fixed ASAP.

As a quick workaround, disable the [Update Bridging Header and PCH files](https://support.swiftify.com/hc/en-us/articles/360015696152-Update-Bridging-Header-and-PCH-files) option - this will very likely avoid creating this file (which is supposed to contain the Swift conversion of the PCH file).

**Comment by alex-swiftify** [comment]
@arlomedia 
This has been fixed as follows:
1) ProjectName-Prefix.swift file is not created for a project with an existing PCH file (this will be effective since the next macOS app update planned within a week).
2) PCH file won't be created or updated during every conversion (but only during the creation of the Bridging Header).
