### ISSUE TITLE
Show file groups in project converter?

### ISSUE THREAD

**Issue by arlomedia** [Swiftify-Corp/Swiftify#150]
My app has about 400 class files, all in a Classes directory in my project directory. I guess this is a bad design, but it's never been a problem because I have the files organized into folders in Xcode (what Xcode calls "groups"). However, when I open the Swiftify project converter, it just reads the file system directories and shows all those classes in one long list. This makes it hard to pick out related classes to convert together. So a feature request is to read the groupings from the Xcode project file and display the files with those same groupings in the project converter. Thanks for considering!

**Comment by alex-swiftify** [comment]
@arlomedia Your request is well understandable, but difficult with our current design :(
Currently, we are parsing the Xcode project on the back-end, but grouping files on the client-side requires parsing the Xcode project file on the front-end side.

We are planning to implement searching and filtering through the list of files soon.
For this report, I'm definitely recording your vote, but that will take time to implement.

**Comment by arlomedia** [comment]
Okay. I've noticed something else that might be a possible easier improvement. I have a long list of classes, and some are grouped with common prefixes. For example, I'm working through the files starting with "MIDI," a few files at a time. Each time the project converter finishes a conversion, it selects several files in the file list and scrolls the file list to the last of those files. I think maybe the project converter is selecting every file related to the most recently converted files, as a suggestion of what files to work on next? But the result is that I keep having to scroll all the way back to the "MIDI" files I wanted to work on next. Perhaps the suggested files (if that's what's happening) could still be selected, but without changing the scroll position.

**Comment by alex-swiftify** [comment]
Thanks, @arlomedia for the suggestion.
Actually, the files highlighted in the project view are files affected by the conversion (sometimes if you convert a single file, other dependencies are also updated).
We will either persist the tree view position or make it a configurable option to disable the feature highlighting these files.

**Comment by arlomedia** [comment]
Got it. Unless the list of files is very short, I feel like automatically scrolling to the last selected file isn't very useful because you'd still have to scroll manually through the whole list to see the others. So just eliminating the auto-scrolling would address my situation, without hampering people who are using that feature.

Now that I know what the selections mean, I could use that, too, and it would be even better if the selected results were displayed together, perhaps as a list in the console or in a popup window after the conversion finishes. That would have the added benefit if making the list persistent so I could refer back to it if needed after performing the next batch of conversions.

**Comment by alex-swiftify** [comment]
@arlomedia The issue with automated scrolling has been finally resolved - this will be present in the next version of Swiftify for Xcode (5.10.1).
Now no scrolling will occur after converting a large number of files.

Showing file groups is currently not planned for the reasons described above (parsing the Xcode project file on the front-end side doesn't fit well into the current project architecture, unfortunately).
