### ISSUE TITLE
Handling comments in property declarations

### ISSUE THREAD

**Issue by arlomedia** [Swiftify-Corp/Swiftify#153]
I sometimes comment the properties in my Objective-C header files. Here's an example:

`@property (nonatomic, strong) DocumentViewer *externalViewer; // this will be set in the main viewer and nil in the external viewer`
`@property (nonatomic, strong) DocumentViewer *mainViewer; // this will be set in the external viewer and nil in the main viewer`
`@property (nonatomic, strong) NSString *documentId;`

Swiftify changes these comments from single-line to multi-line style and moves them to the start of the next line, so the output looks like this:

`var externalViewer: DocumentViewer?`
`/* this will be set in the main viewer and nil in the external viewer */    var mainViewer: DocumentViewer?`
`/* this will be set in the external viewer and nil in the main viewer */    var documentId = ""`

I would prefer keeping the commenting style as I wrote it, but most important is keeping the comment on the same line so the variable on the next line doesn't get lost after the previous line's comment. Hopefully this won't be hard to address.

My source file uses Linux (LF) line endings, if that matters.

**Comment by arlomedia** [comment]
Here's a simplified version in case the line wrapping above makes this unclear.

Input:

`@property NSString *prop1; // comment for prop1`
`@property NSString *prop2; // comment for prop2`
`@property NSString *prop3;`

Output:

`var prop1: String`
`/* comment for prop1 */ var prop2: String`
`/* comment for prop2 */ var prop3: String`

**Comment by alex-swiftify** [comment]
@arlomedia Interesting, I even wasn't aware our converter is doing that.
The handling of comments is not an easy task, but we'll take a look at what could be improved here.

**Comment by alex-swiftify** [comment]
Implemented (will be available after the next converter update).

Input:
```
@property NSString *prop1;          // comment for prop1
@property NSString *prop2, *prop3;   // comment for prop2
@property NSString *prop4;
@property NSString *prop5, *prop6;
```

Output:
```
var prop1: String? // comment for prop1
var prop2: String? // comment for prop2
var prop3: String?
var prop4: String?
var prop5: String?
var prop6: String?
```
