### ISSUE TITLE
compatibility_alias to typealias

### ISSUE THREAD

**Issue by arlomedia** [Swiftify-Corp/Swiftify#156]
I had this in my Objective-C code, to ignore a framework that isn't supported by the simulator:

@compatibility_alias CABTMIDICentralViewController UIViewController;
@compatibility_alias CABTMIDILocalPeripheralViewController UIViewController;

Swiftify converted it to this, which created a build error when building for the simulator:

var aCABTMIDICentralViewController: compatibility_alias?
var aCABTMIDILocalPeripheralViewController: compatibility_alias?

I changed it to this, which builds and runs as expected:

typealias CABTMIDICentralViewController = UIViewController
typealias CABTMIDILocalPeripheralViewController = UIViewController

I got the idea from this Swift proposal. It's four years old and I couldn't tell if it has been implemented or if it just happens to work already with this simple use case:

https://forums.swift.org/t/objective-c-s-compatibility-alias-swift-s-typealias/3215

**Comment by alex-swiftify** [comment]
Fixed (now `@compatibility_alias` is handled similarly to `typedef`).
Will be available since the next converter update.

Converter output:
```
typealias UIViewController = CABTMIDICentralViewController
typealias UIViewController = CABTMIDILocalPeripheralViewController
```
