### ISSUE TITLE
Minor Conversion fix with string interpolation

### ISSUE THREAD

**Issue by Ibrahimhass** [Swiftify-Corp/Swiftify#169]
Minor conversion fix
https://swiftify.me/bm3ccv

**Objective-C Code**  
`#define kBanner(s) [NSString stringWithFormat:@"Banner %d",s]`
**Converted Swift Code**
```
func kBanner(_ s: Any) -> String {
    "Banner \s"
}
```
**Fixed Code**
```
func kBanner(_ s: Any) -> String {
    "Banner \(s)"
}

```

**Comment by alex-swiftify** [comment]
Fixed.
Converter output:
```
func kBanner(_ s: Any) -> String {
    "Banner \(s)"
}
```
