### ISSUE TITLE
Issue with converting NSLocalized String

### ISSUE THREAD

**Issue by Ibrahimhass** [Swiftify-Corp/Swiftify#174]
**Original Objective-C code**

```
NSLocalizedString(@"dsf", comment: @"dsv"); 
NSLocalizedString(sdvf, comment: @"sdv");
```

**Converted Swift Code**
```
NSLocalizedString(@", comment: dsf)
NSLocalizedString(sdvf, comment: comment)
```

**Correct Swift Code**

```
NSLocalizedString("dsf", comment: "dsv"); 
NSLocalizedString("sdvf", comment: "sdv");

```

**Comment by alex-swiftify** [comment]
@Ibrahimhass If you remove the `comment: ` "argument label", this works just fine: https://swiftify.me/0ksr6k

Since Objective-C `NSLocalizedString()` is actually a #define macro: https://share.getcloudapp.com/RBulxqPk
I can hardly understand what `comment:` stands for.
Changing `comment` to e.g. `comment2` also compiles, so it seems like the compiler ignores this name: https://share.getcloudapp.com/nOuPZemD

I will try adding support for this, but I can't easily find such a syntax elsewhere in Objective-C.

Where does this syntax come from?

**Comment by Ibrahimhass** [comment]
@alex-swiftify `NSLocalizedString` is a macro 
NSLocalizedString can also be used as a format string in NSString `+stringWithFormat:.` In these cases, it’s important to use the comment argument to provide enough context to be properly translated.

`self.title = [NSString stringWithFormat:NSLocalizedString(@"%@'s Profile", @"{User First Name}'s Profile"), user.name];
`

Reference:
https://nshipster.com/nslocalizedstring/#:~:text=NSLocalizedString%20is%20a%20Foundation%20macro,sufficient%20context%20for%20accurate%20translation.

**Comment by alex-swiftify** [comment]
@Ibrahimhass It seems like you didn't fully understand my above comment.

We fully support the NSLocalizedString macro: https://swiftify.me/0ksr6k
... but not such an exotic usage of it (which I haven't found anywhere online): https://swiftify.me/0ksr6k/1

In the last sample, someone tries to add something like an "argument label" (`comment:`) to the Objective-C code that invokes a macro, and this somehow compiles.
I cannot find any reference that you can pass a named argument when calling an Objective-C macro.

Fixing this is not very trivial, so I'm double-checking with you first.

**Comment by Ibrahimhass** [comment]
@alex-swiftify I have mostly seen the comment parameter of NSLocalizedString as `nil`
also as I see in Xcode the second argument is not labeled as a comment `explicitly`
    `NSLocalizedString(@"odds", nil);`
However adding a comment argument also works fine 
`NSLocalizedString(@"ddds",comment: nil);`

Unrelated but the comment argument is used for providing  context in cases like these

`self.title = [NSString stringWithFormat:NSLocalizedString(@"%@'s Profile", @"{User First Name}'s Profile"), user.name];`

I got this code from [here](https://nshipster.com/nslocalizedstring/#:~:text=NSLocalizedString%20is%20a%20Foundation%20macro,sufficient%20context%20for%20accurate%20translation)

**Comment by alex-swiftify** [comment]
@Ibrahimhass I don't see any mention of Objective-C code explicitly specifying the comment argument in the article [here](https://nshipster.com/nslocalizedstring/#:~:text=NSLocalizedString%20is%20a%20Foundation%20macro,sufficient%20context%20for%20accurate%20translation).

I see that this compiles in Objective-C, but it seems to be that someone just copied a Swift code/pattern into Objective-C code.

**Comment by Ibrahimhass** [comment]
@alex-swiftify 

>I see that this compiles in Objective-C, but it seems to be that someone just copied a Swift code/pattern into Objective-C code.

I also think that this is the case.

**Comment by alex-swiftify** [comment]
@Ibrahimhass What is the reason you have reopened this?
I still don't see where did you find the Objective-C code as [in the description](https://share.getcloudapp.com/DOuqz7px).
Please provide a source if this is still actual.

**Comment by Ibrahimhass** [comment]
@alex-swiftify I could not find this exact sample anywhere else online.
It seems that this is not some standard way to declare NSLocalizedStrings.
