### ISSUE TITLE
Incorrect Code conversion

### ISSUE THREAD

**Issue by Ibrahimhass** [Swiftify-Corp/Swiftify#176]
**Objective-C code**

`[self.popoverFlow showBookmarksWith:config completion:cfg.completion];`

**Converted Swift Code**
`popoverFlow.showBookmarks(with: config) cfg.completion`
https://swiftify.me/7x44sw/1

**Correct Conversion**
`popoverFlow.showBookmarks(with: config, completion: cfg.completion)`

**Comment by alex-swiftify** [comment]
Fixed.
Converter output (will be available since the next update):
```
popoverFlow.showBookmarks(with: config, completion: cfg.completion)
```
