### ISSUE TITLE
Side effects of setters should use didSet

### ISSUE THREAD

**Issue by Ceroce** [Swiftify-Corp/Swiftify#178]
Hi,

I think that the following is fairly typical of how to add side effects when a setter is called.

```
// .h
@property (nonatomic) UIColor *ticketColor;

// .m
@synthesize ticketColor = _ticketColor;
-(void)setTicketColor:(UIColor *)ticketColor {
    if(ticketColor == _ticketColor) {
        return;
    }
    _ticketColor = ticketColor;
    
    // Side effect
    self.backgroundView.backgroundColor = ticketColor;
}
```

Unfortunately, the current version of Swiftify performs a literal translation:

```
private var _ticketColor: UIColor?
var ticketColor: UIColor? {
    get {
        _ticketColor
    }
    set(ticketColor) {
        if ticketColor == _ticketColor {
            return
        }
        _ticketColor = ticketColor

        // Side effect
        backgroundView?.backgroundColor = ticketColor
    }
}
```

I'd expect the following:

```
var ticketColor: UIColor? {
    didSet {
        backgroundView?.backgroundColor = ticketColor
    }
}
```

I guess the conversion is not easy but if you could fix this, it would be a nice time-saver, since it occurs frequently in my code base.
Thanks!

Renaud

**Comment by alex-swiftify** [comment]
Thanks, @Ceroce for reporting!

Right you are - detecting all cases that could be converted to didSet is not an easy task. 
Good news is that your vote here is not the first one, so we are very likely to implement this soon. 
Stat tuned, and track this ticket for the status.

**Comment by Ceroce** [comment]
Thanks Alex, I'm looking forward for it!

**Comment by alex-swiftify** [comment]
Hi @Ceroce,

It's been really a while (thanks for your patience!), but this is finally in progress.

I've got a question regarding the pattern you are using, and whether it's safe to convert it into a `didSet` property observer.

Referring to [this article](https://medium.com/the-andela-way/property-observers-didset-and-willset-in-swift-4-c3730f26b1e9),

>One thing to note is that `willSet` and `didSet` will never get called on setting the initial value of the property. It will only get called whenever you set the property by assigning a new value to it. It will always get called even if you assign the same value to it multiple times.

1. a) your original Objective-C code will **not** call the "side effect" code if the same value is assigned to `ticketColor`
1. b) your suggested Swift code using `didSet` accessor will always call the "side effect" code, even if the same value is assigned

Also:
2. a) your original Objective-C code will call the "side effect" code even if the property is assigned from an initializer
2. b) your suggested Swift code will **not** call the "side effect" code if the property is assigned from an initializer

I agree that in most cases, the suggested translation would be fine, and it's up to the developer to take care of the possible quirks (1) and (2).
However, I'm not 100% sure if we should convert your suggested pattern to use a `didSet` property observer.

Of course, the following case without a condition should be converted to `didSet`:

```
@property (nonatomic) UIColor *ticketColor;

-(void)setTicketColor:(UIColor *)ticketColor {
    _ticketColor = ticketColor;
    
    // Side effect
    self.backgroundView.backgroundColor = ticketColor;
}
```

What's your opinion?

**Comment by nickasd** [comment]
That's an interesting case. Personally, I would also expect the converter to produce a property with `didSet`. If the converter didn't do it, I would then do it myself manually. Those two differences between ObjectiveC and Swift are something that probably every programmer will figure out sooner or later; I guess most programmers will assume that they behave the same, and at some point learn the differences. That's how it went for me: I started using properties and `didSet`, and when I noticed that something wasn't behaving as I imagined, I debugged and learned it the hard way.

Summarizing: the suggested change will not produce code that behaves exactly the same, but many people will probably be annoyed if the converter didn't do it, and only later learn the difference. Though I could also understand if someone gets upset if the converter produces slightly wrong code. Perhaps you could add an option that defaults to producing the correct code, and enabling it would produce this optimization that most people will probably expect anyway?

**Comment by alex-swiftify** [comment]
Thanks, @nickasd for the detailed feedback.

I completely agree that if we implement this, we will have to make this behavior configurable.

The major problem with configurable options is that most users never change them, so if we don't enable this by default, this is going to be unnoticed by most users.

That said, if we implement this (which is not easy as we'll have to support other variations of the code like [this one](https://swiftify.me/igmt6z), I'd make this configurable and **on** by default (despite the side effects).

Yet need to understand how frequently the pattern suggested in this ticket occurs in real-world projects (in order to judge whether it's worth the effort).

**Comment by alex-swiftify** [comment]
Implemented support for the pattern suggested in this ticket.
Made this a configurable option (turned on by default): [Generate `didSet` property observers (if possible)](https://support.swiftify.com/hc/en-us/articles/12483807989778).

Input:
```

@interface Test : UITableView

@property (nonatomic) UIColor *ticketColor;

@end

@implementation Test

@synthesize ticketColor = _ticketColor;

-(void)setTicketColor:(UIColor *)ticketColor {
    if(ticketColor == _ticketColor) {
        return;
    }
    _ticketColor = ticketColor;
    
    // Side effect
    self.backgroundView.backgroundColor = ticketColor;
}

@end
```

Converter output:
```
class Test: UITableView {
    var ticketColor: UIColor? {
        didSet {
            // Side effect
            backgroundView?.backgroundColor = ticketColor
        }
    }
}
```

**Comment by Ceroce** [comment]
Hi Alex!
Sorry to be late at the party, but I was on holiday.
Unfortunately, I can not try this new feature; in two years I had the time to switch jobs and Objective-C is no longer on the menu.

Anyway, I'm going to try to answer your questions:

> 1.a) your original Objective-C code will not call the "side effect" code if the same value is assigned to ticketColor

This is idiomatic in Objective-C; I see the `if(property != _property)` as an optimization, since side effects might be complex actions.
 
> 1.b) your suggested Swift code using didSet accessor will always call the "side effect" code, even if the same value is assigned

I agree that this is not coherent, but the idiom is different in Objective-C and Swift. I guess in Swift this optimization is less needed because of the heavy use of value types.

> 2. a) your original Objective-C code will call the "side effect" code even if the property is assigned from an initializer
> 2. b) your suggested Swift code will not call the "side effect" code if the property is assigned from an initializer

Yes, but calling `self.property = value` in the init is a mistake.
Unlike Swift, Objective-C has no syntax to provide a default value at the declaration of the variable, therefore it must be done at init using `_property = defaultValue`.

You explicitly don't wan't to trigger the side effect at init! Hence the behaviour in Swift, that setting a property at init won't call `didSet`.

> the suggested change will not produce code that behaves exactly the same, but many people will probably be annoyed if the converter didn't do it

Exactly. I had a lot of occurrences in my code base and I had to make the code "swifty" manually. My proposition came for the fact that this is idiomatic in Objective-C and it will probably appear a lot in other code bases as well.

**Comment by alex-swiftify** [comment]
@Ceroce Thanks for taking the time to reply to this!

I agree about everything, here is the only thing that I wanted to comment on.

>Yes, but calling `self.property = value` in the init is a mistake.
>Unlike Swift, Objective-C has no syntax to provide a default value at the declaration of the variable, therefore it must be done at init using `_property = defaultValue`.

Currently, Swiftify converts `_property = defaultValue` in the initializer to `property = defaultValue` ([sample](https://swiftify.me/cnyq1m)).

You would probably expect the above sample to produce the following instead:
```
class Test: UITableView {
    var ticketColor: UIColor? = .red {
        didSet {
            // Side effect
            backgroundView?.backgroundColor = ticketColor
        }
    }
}
```

That's an interesting suggestion, although not very easy for the converter.
For now, this should be manually addressed by the user after the conversion.

**Comment by renaud-diabeloop** [comment]
@alex-swiftify yes, that is the code that I would expect, in an ideal world. Like everyone, I played with Large Language Models lately, and I realise that they might produce more Swifty code, but that their output can not be relied on.

Swiftify applies a more literal translation and as a result, its output can generally be trusted. It fits what I need from such a tool: convert large quantities of code quickly and reliabily. Some refactoring can take place later.
