### ISSUE TITLE
Parser issue when converting NS_AVAILABLE and NS_DEPRECATED

### ISSUE THREAD

**Issue by Ibrahimhass** [Swiftify-Corp/Swiftify#184]
**Objective-C code:**

```
- (void)peripheralDidUpdateName:(CBPeripheral *)peripheral NS_AVAILABLE(10_9, 6_0) {
    NSLog(@"peripheralDidUpdateName");
}

```

This results in a converter [error](https://swiftify.me/agsr1d).

However, this one works just [fine](https://swiftify.me/agsr1d/1)

**Objective-C Code:**

```
- (void) newMethod API_AVAILABLE(macosx(10.13), ios(11)) {
    
}
```

**Converted Swift Code:**

```
@available(macOS 10.13, iOS 11, *)
func newMethod() {

}
```

 **NS_DEPRECATED**

**Objective-C Code:**

```
- (void)newMethod NS_DEPRECATED(10_7, 10_13, 5_0, 8_0){
}

```

Results in [error](https://swiftify.me/agsr1d/2)

**Alternative Swift Code**
```
@available(iOS, deprecated: 8.0)
@available(macOS, deprecated: 10.13)
func newMethod() {
}
```

https://www.avanderlee.com/swift/available-deprecated-renamed/

**Comment by alex-swiftify** [comment]
@Ibrahimhass Fixed (along with https://swiftify.atlassian.net/browse/SWC-1103). 
Will be available since the next converter update.

Converter output:
```
@available(macOS 10.9, iOS 6.0, *)
func peripheralDidUpdateName(_ peripheral: CBPeripheral) {
    print("peripheralDidUpdateName")
}
```
