### ISSUE TITLE
Incorrect conversion of CAShapeLayer.lineCap and CAShapeLayer.lineJoin

### ISSUE THREAD

**Issue by Ibrahimhass** [Swiftify-Corp/Swiftify#195]
**Original Objective-C code**

```
self.progressLayer = [CAShapeLayer layer];
self.progressLayer.contentsScale = [[UIScreen mainScreen] scale];
self.progressLayer.fillColor = [UIColor clearColor].CGColor;
self.progressLayer.lineCap = kCALineJoinBevel;
self.progressLayer.lineJoin = kCALineJoinBevel;
[self.layer addSublayer:self.progressLayer];
self.progressLayer.strokeEnd = 0;
```

**Converted Swift Code**

```
progressLayer = CAShapeLayer()
progressLayer.contentsScale = UIScreen.main.scale
progressLayer.fillColor = UIColor.clear.cgColor
progressLayer.lineCap = CAShapeLayerLineCap(rawValue: CAShapeLayerLineJoin.bevel.rawValue)
progressLayer.lineJoin = .bevel
layer.addSublayer(progressLayer)
progressLayer.strokeEnd = 0
```
https://swiftify.me/vsckup

**Required change in Conversion Result:**

```
progressLayer.lineCap = kCALineJoinBevel
.progressLayer.lineJoin = kCALineJoinBevel
```

**Comment by alex-swiftify** [comment]
@Ibrahimhass 
For me it looks like the assignment in this line:
```
self.progressLayer.lineCap = kCALineJoinBevel;
```
is a mistake in the Objective-C code in the first place.

The `lineCap` property is of type `CAShapeLayerLineCap`:
https://developer.apple.com/documentation/quartzcore/cashapelayerlinecap
and according to the documentation it should be assigned to `kCALineCap* ` constant.

Our converter understands that a constant kCALineJoinBevel (of type [CAShapeLayerLineJoin](https://developer.apple.com/documentation/quartzcore/cashapelayerlinejoin?language=objc)) is assigned to a property lineCap of type CAShapeLayerLineCap, thus it generates this code to convert between 2 enum types:
```
CAShapeLayerLineCap(rawValue: CAShapeLayerLineJoin.bevel.rawValue)
```
which looks like the most appropriate translation to me.

If I change the input code like this (to assign kCALineCapButt):
```
self.progressLayer = [CAShapeLayer layer];
self.progressLayer.contentsScale = [[UIScreen mainScreen] scale];
self.progressLayer.fillColor = [UIColor clearColor].CGColor;
self.progressLayer.lineCap = kCALineCapButt;
self.progressLayer.lineJoin = kCALineJoinBevel;
[self.layer addSublayer:self.progressLayer];
self.progressLayer.strokeEnd = 0;
```
the output looks as you would expect:
```
progressLayer = CAShapeLayer()
progressLayer.contentsScale = UIScreen.main.scale
progressLayer.fillColor = UIColor.clear.cgColor
progressLayer.lineCap = .butt
progressLayer.lineJoin = .bevel
layer.addSublayer(progressLayer)
progressLayer.strokeEnd = 0
```

Closing this out, if you have any objections let me know.
