### ISSUE TITLE
Feature Request: Expose CLI for the offline converter

### ISSUE THREAD

**Issue by amorde** [Swiftify-Corp/Swiftify#201]
I'd like to be able to incorporate running Swiftify as part of other existing automation scripts and tools that I have for performing code changes. Something like the following:

```
swiftify convert /path/to/object.h /path/to/object.m
```

**Comment by alex-swiftify** [comment]
Thanks, @amorde for the suggestion!

Since we have originally discussed this feature with your team before your company have signed up to use the software,
this is going to be implemented.
Please suggest a priority - would you like to prioritize this over other conversion issues, or take care of the conversion issues first?
Alternatively, roughly suggest the timeline by when do you absolutely need the CLI feature implemented.

**Comment by amorde** [comment]
Yes I would prioritize this over other requests as long as the offline converter is supported. For us specifically, we have some tools that we can use to adjust the output of the CLI (once there is one) so that would give us a path to working around any issues with the resulting code

**Comment by alex-swiftify** [comment]
@amorde Interesting, thanks for the feedback!
I'll research the options that we have to suggest this and get back to you.

**Comment by alex-swiftify** [comment]
@amorde Just FYI, we have started implementing the CLI version.
Thanks for your patience!

@Ibrahimhass Please post any progress updates here once available.

**Comment by alex-swiftify** [comment]
@amorde I'm happy to inform you that the command-line interface has been implemented and it's available in just released version 5.6.2 of the Offline Converter: https://share.getcloudapp.com/6quz7Wzp

Your feedback is welcome!

**Comment by amorde** [comment]
Have already tried it and so far it works great! Thank you so much for adding it

**Comment by alex-swiftify** [comment]
Awesome, thanks @amorde for confirming!
We have built the CLI version just for you, so I’d appreciate any feedback in the future as well!
It’s interesting to know how would it integrate to your existing build process - feel free to share once you’ve made it work.
