### ISSUE TITLE
Category extensions are not correctly translated

### ISSUE THREAD

**Issue by AlexanderJ** [Swiftify-Corp/Swiftify#205]
In Objective-C I can do extensions by:
```
@interface ClassName (CategoryName)
- someMethod(); 
@end
```
See also:
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/CustomizingExistingClasses/CustomizingExistingClasses.html

In swift the category is irrelevant thus it should be converted to:
```
extension ClassName {
    func someMethod()
}
```
but instead I get:
```
class ClassName: Category {
    func someMethod()
}
```

**Comment by alex-swiftify** [comment]
@AlexanderJ How exactly do you get the result you mentioned?
As far as I see, our current output matches your expectations: https://swiftify.me/v7rfqh
Please post the exact input code, and the way how you have converted it, or preferably a swiftify.me link as my above link.

**Comment by alex-swiftify** [comment]
@AlexanderJ Closing as the current converter output matches your expectations.
In the case I'm missing anything let me know.
