### ISSUE TITLE
property getters in protocol

### ISSUE THREAD

**Issue by AlexanderJ** [Swiftify-Corp/Swiftify#206]
Lets assume I have this:
```
protocol A {
    - (nullable id<SomeProtocol>)someValue;
    - (nullable NSString*)someOtherValue;
};

@interface B: NSObject<A> {
@property (nonatomic, readwrite, nullable) id<SomeProtocol> someValue;
@property (nonatomic, readwrite, nullable) NSString *someOtherValue;
};

@implementation B {
@synthesize someValue;
@synthesize someOtherValue;
};
```
Then I would expect this Swift code:
```
protocol A {
    var someValue: SomeProtocol? { get }
    var someOtherValue: String? { get }
}

class B {
    var someValue: SomeProtocol?
    var someOtherValue: String?
}
```
I get the correct class B, but I get this protocol instead:
```
protocol A {
    func someValue() -> SomeProtocol?    
    func someOtherValue() -> String?
}
```

**Comment by alex-swiftify** [comment]
I got you, @AlexanderJ.
We have recently improved support for overridden properties - https://github.com/Swiftify-Corp/Swiftify/issues/186, but those changes didn't support protocol properties so far.
Will look into this as time permits.

**Comment by alex-swiftify** [comment]
The code in the description is some mix of Objective-C and Swift and does not compile, so I assume the following was intended as the input:
```
\@protocol A
- (nullable id<SomeProtocol>)someValue;
- (nullable NSString*)someOtherValue;
@end

@interface B: NSObject<A>
@property (nonatomic, readwrite, nullable) id<SomeProtocol> someValue;
@property (nonatomic, readwrite, nullable) NSString *someOtherValue;
@end

@implementation B
@synthesize someValue;
@synthesize someOtherValue;
@end
```

**Comment by alex-swiftify** [comment]
After a review, the conversion of the above code already converted protocol methods to property declarations: 
![image](https://user-images.githubusercontent.com/3234792/170541685-c2da1141-ef87-4011-be57-efe53f1d17a8.png).

The only change needed was to add a `{ get }` accessor to protocol methods converted to properties.

Converter output for the code from my previous comment:
```
protocol A: AnyObject {
    var someValue: SomeProtocol? { get }
    var someOtherValue: String? { get }
}

class B: NSObject, A {
    var someValue: SomeProtocol?
    var someOtherValue: String?
}
```
