### ISSUE TITLE
id translates to anId

### ISSUE THREAD

**Issue by AlexanderJ** [Swiftify-Corp/Swiftify#207]
Code like this
```
@interface T
@property (assign, strong) NSString *id;
@end
```
translates to:
```
//  Converted to Swift 5.5 by Swiftify v5.5.24623 - https://swiftify.com/
class T {
    var anId: String?
}
```
However, this does not translate back in a compatible way to existing swift code as it is exported to Objective-C as anId as well.
To correctly bridge to existing code I would expect this:
```
//  Converted to Swift 5.5 by Swiftify v5.5.24623 - https://swiftify.com/
class T {
    var `id`: String?
}
```

**Comment by AlexanderJ** [comment]
\`

**Comment by AlexanderJ** [comment]
The symbol \`id\`

**Comment by AlexanderJ** [comment]
With the back ticks included compiles in Swift and bridges correct.

**Comment by alex-swiftify** [comment]
@AlexanderJ Thanks for reporting.
We normally do this for reserved identifiers, but I agree that `id` should not be renamed here.

**Comment by AlexanderJ** [comment]
I think the backtickw work for all reserved identifiers

**Comment by alex-swiftify** [comment]
@AlexanderJ Yeah, using backticks is definitely an option - will revisit that.

**Comment by alex-swiftify** [comment]
Related task: https://swiftify.atlassian.net/browse/SWC-987

**Comment by alex-swiftify** [comment]
Fixed (will be available since the next update).

Converter output:
```
class T {
    var id: String?
}
```
