### ISSUE TITLE
Handling of prepositions

### ISSUE THREAD

**Issue by AlexanderJ** [Swiftify-Corp/Swiftify#212]
If I write this in Objective-C:
```
@interface TestClass: NSObject
- (void) requestWith: (NSObject*)value and:(int)number;
- (void) requestWithMethod: (NSObject*)method and:(int)number;
- (void) requestForStuff: (NSObject*)stuff and:(int)number;
@end
```

I get this:
```
//  Converted to Swift 5.5 by Swiftify v5.5.24623 - https://swiftify.com/
class TestClass: NSObject {
    func request(with value: NSObject?, and number: Int) {    }
    func request(withMethod method: NSObject?, and number: Int) {    }
    func request(forStuff stuff: NSObject?, and number: Int) {    }
}
```

But Swift style would be:
```
class TestClass: NSObject {
    func request(_ value: NSObject?, and number: Int) {  }
    func request(method: NSObject?, and number: Int) { }
    func request(stuff: NSObject?, and number: Int) {  }
}
```
This is the case for "With", but I'm unsure regarding "for" and other prepositions.

**Comment by alex-swiftify** [comment]
@AlexanderJ The Swiftify's output almost exactly matches the Xcode's [Generated Swift 5 Interface](https://take.ms/BaC7u) for your sample (except for using `?` optional specifiers instead of `!`, which is the "by design" default for Swiftify):
```
open class TestClass : NSObject {
    open func request(with value: NSObject!, and number: Int32)
    open func request(withMethod method: NSObject!, and number: Int32)
    open func request(forStuff stuff: NSObject!, and number: Int32)
}
```
... so I see nothing to "fix here".

**Comment by AlexanderJ** [comment]
The example I gave generates the same interface to objective-c as the swiftified version. However, AFAIK the example adheres to the recommended Swift interface.

**Comment by AlexanderJ** [comment]
Maybe something for a switch.

**Comment by alex-swiftify** [comment]
@alex-swiftify At Swiftify, we follow the "omit needless words" algorithm exactly as used by Xcode.
I'll prioritize https://swiftify.atlassian.net/browse/SWC-441 to make this behavior configurable, but this may take some time to go live.
