### ISSUE TITLE
NS_OPTIONS/NS_ENUM are not correctly translated

### ISSUE THREAD

**Issue by AlexanderJ** [Swiftify-Corp/Swiftify#214]
Neither NS_OPTIONS nor NS_ENUM are correctly converted. This is quite tedious also when not converting the enum/options itself to be able to still use them from objective-c as this requires a lot of manual work to fix.

Example: https://swiftify.me/lc8ui2/1

I would expect:
```
enum PREConverseLogMode : Int {
    case disabled
    case enabled
}
```
and
```
struct PREConverseLogType : OptionSet {
    let rawValue: Int

    static let networking = Self(rawValue: (1 << 0))
    static let operation = Self(rawValue: (1 << 1))
    ...
}
```
instead. This is how Xcode bridges this (remove prefix and make first character after prefix lower case). All uses should be translated accordingly as well. Thus I could use the same definition from Swift and Objective-C.

I consider this high priority.

**Comment by alex-swiftify** [comment]
Thanks, @AlexanderJ.
It looks like Xcode uses pretty difficult rules to strip the part of the identifiers.
We will look into that, although the complete solution may appear complex.

Currently, we only support cases when the enum identifier starts with the enum name ([example](https://swiftify.me/vtqd79)).

**Comment by AlexanderJ** [comment]
Indeed. I found the rules [here](https://github.com/apple/swift/blob/main/docs/CToSwiftNameTranslation.md).

**Comment by alex-swiftify** [comment]
@AlexanderJ Great, thanks for the reference!

**Comment by alex-swiftify** [comment]
Fixed according to Apple's guidelines.

Check the link from the summary for the updated converter output: https://swiftify.me/lc8ui2/1
