### ISSUE TITLE
No $399 plan for me

### ISSUE THREAD

**Issue by dhoerl** [Swiftify-Corp/Swiftify#218]
![Screen Shot 2022-04-12 at 1 58 07 PM](https://user-images.githubusercontent.com/812695/163024967-a31c471d-2158-48ad-9c4a-35b51ce4c1fa.png)

**Comment by alex-swiftify** [comment]
@dhoerl Please post a screenshot of what you see when you move the "slider under "Objective-C files/year" to the "300" mark?

**Comment by dhoerl** [comment]
I stupidly did not realize the sliders were controls. All is well.
