### ISSUE TITLE
Bad handling of error/exception style

### ISSUE THREAD

**Issue by AlexanderJ** [Swiftify-Corp/Swiftify#224]
In this example the Objective-C code uses a return value error code:
https://swiftify.me/1a48mv

The converted Swift code uses an empty catch block, instead of eliminating the error variable and doing the error handling in the catch block.

**Comment by alex-swiftify** [comment]
Fixed. Converter output:
```
if value is [AnyHashable : Any] {
    do {
        deserializedValue = try PREConverseConceptModel(dictionary: value as? [AnyHashable : Any])
    } catch {
        PREConverseLog(kPREConverseLogTypeModel, kPREConverseLogFlagError, kPREConverseLogLevel0, error?.localizedDescription)
    }
}
```
