### ISSUE TITLE
inconsistent parameter naming

### ISSUE THREAD

**Issue by AlexanderJ** [Swiftify-Corp/Swiftify#227]
Parameters to methods get different conversion results depending on context. IMHO the parameter names should be chosen in a way compatible with existing objective-c code, regardless of wether some of this code has also be converted.

In the example https://swiftify.me/7a5al3/1 there are several inconsistencies. If you comment out or in formatValue and stringFromValue the calling method arguments are either `for` or `forDataType`.

If you remove @implementation and @end the behavior for formatValue/valueFormatForField is always the same regardless of wether formatValue is commented in or not (not sure whether its consistent with Objective-C code though), but the other method pair stringFromValue/updateMainContentUI is still inconsistent.

**Comment by alex-swiftify** [comment]
@AlexanderJ This feature is called [Omit Needless Words](https://github.com/apple/swift-evolution/blob/main/proposals/0005-objective-c-name-translation.md) and it was introduced in Swift 3.

How it works: when an argument of type `PREConverseAppDataType` have been passed as a `forDataType` parameter, 
the `DateType` part (which is the common words between the argument label and the type name) are stripped from the type name.

This is how Xcode itself translates this method signature from Objective-C to Swift, too.

However, for this to happen, our converter has to know the type of the `forDataType` argument, and that is only when the `formatValue:forDataType:` method is actually declared (and its declaration is included in the conversion).

I understand through that you want this behavior to be consistent, and the best solution I see is to make this "Omit Needless Words" behavior configurable.
Thus I'm closing this issue in favor of https://swiftify.atlassian.net/browse/SWC-1188 which is going to be addressed soon.
