### ISSUE TITLE
Swiftify does not convert symbols that are renamed in Swift

### ISSUE THREAD

**Issue by emish** [Swiftify-Corp/Swiftify#231]
Lots of compiler errors are left after conversion in the form of:
`ABCFoo has been renamed to Foo`

for types that have a specific objc name
```
@objc(ABCFoo)
class Foo {}
```

**Comment by alex-swiftify** [comment]
@emish I gave it a thought, and it's pretty unlikely that we will implement parsing of the Swift files in the nearest time, at least unless we get more votes for this feature.
It's interesting that you've got dozens or hundreds of such cases in your project.
For my better understanding, why is that the case?
I guess you've had a convention e.g. to prefix all class names with your company's XYZ prefix in Objective-C, but not in Swift?

If the above is your actual use case, we've got other reports like this one.
An option to remove the prefix from Objective-C type names is possible to add if that's used widely and consistently within your project.
