### ISSUE TITLE
Reachability Conversion Incorrect

### ISSUE THREAD

**Issue by dhoerl** [Swiftify-Corp/Swiftify#233]
I had this line of Objective-C code in a file conversion:

`if ([[Reachability reachabilityForInternetConnection] currentReachabilityStatus] == NotReachable) {`

Swiftly converted it to this:
`Reachability().currentReachabilityStatus() == .notReachable`

I only noticed this as I got a crash in the above (and only one on multiple runs of the app). The correct conversion is:

`Reachability.forInternetConnection().currentReachabilityStatus() == .notReachable`

**Comment by alex-swiftify** [comment]
Fixed.

Input:
```
if ([[Reachability reachabilityForInternetConnection] currentReachabilityStatus] == NotReachable) {
}
```

Output:
```
if Reachability.forInternetConnection().currentReachabilityStatus() == NotReachable {
}
```
