### ISSUE TITLE
Semantic error when accessing properties

### ISSUE THREAD

**Issue by AlexanderJ** [Swiftify-Corp/Swiftify#237]
In this code example:
https://swiftify.me/he9dvo

the resulting code modifies a class attribute. The resulting code however, leads to an error as it tries to modify a local constant.

**Comment by AlexanderJ** [comment]
Possible solution:
'''swift
func fulfillExpectation() {
        expectation?.fulfill()
        expectation = nil
}
'''

**Comment by alex-swiftify** [comment]
Related issue to be reviewed: https://github.com/Swiftify-Corp/Swiftify/issues/81
