### ISSUE TITLE
GCD queue creation conversion ignores concurrency attribute

### ISSUE THREAD

**Issue by mjohnson12** [Swiftify-Corp/Swiftify#241]
`dispatch_queue_create("com.company.concurrentAccessQueue", DISPATCH_QUEUE_CONCURRENT);` gets converted to `DispatchQueue(label: "com.company.concurrentAccessQueue")`.

It's missing the concurrency  attribute so it creates a serial queue instead.

This was found using the standalone converter version 5.6.1.

**Comment by alex-swiftify** [comment]
Thanks, @mjohnson12 for reporting!

Just to be completely sure, do you expect the following as the output for your case?

```
DispatchQueue(label: "com.company.concurrentAccessQueue", attributes: .concurrent)
```

**Comment by mjohnson12** [comment]
Yes

**Comment by alex-swiftify** [comment]
@mjohnson12 Thanks for confirming.
It's fixed as I suggested above.
The change will be included in the next Offline Converter update.
