### ISSUE TITLE
postincrement operator handled too late

### ISSUE THREAD

**Issue by rob-miller** [Swiftify-Corp/Swiftify#244]
No doubt an edge case and vulnerable to many style criticisms but...

[here in voFunction.m](https://github.com/rob-miller/rTracker/blob/0ec6cf2a268946dc957982f7d3db01a8a1272a52/Classes/voFunction.m#L505-L507) again I have (observe `currFnNdx`, and notably this is formatted differently on Github than in Xcode so weird whitespace characters):

    while (self.currFnNdx < maxc) {
        // recursive function, self.currFnNdx holds our current processing position
		NSInteger currTok = [(self.fnArray)[self.currFnNdx++] integerValue];
		if (isFn1Arg(currTok)) {
                     ...
                    [big massive ugly code]
                    [further modifies self.currFnNdx]
                    ....
		}
	}

Swiftify generates this as:

        while currFnNdx < maxc {
            // recursive function, self.currFnNdx holds our current processing position
            let currTok = ((fnArray)?[currFnNdx] as? NSNumber)?.intValue ?? 0
            if isFn1Arg(currTok) {
            ....
            }
        }
        currFnNdx += 1

It seems like ~Swift should have a postincrement operator~ :-) the `currFnNdx` increment should happen immediately after the `let` assignment that uses the value.

**Comment by alex-swiftify** [comment]
@rob-miller Thanks for reporting, I confirmed the problem (or even a few problems) given your sample code.
This will be addressed for sure.

**Comment by alex-swiftify** [comment]
Related issue: https://swiftify.atlassian.net/browse/SWC-725
Code sample to reproduce current issues: https://swiftify.me/l3ptt4

**Comment by alex-swiftify** [comment]
This one has been fixed, and will be included in the next converter update after some polishing. 
Thanks again for reporting!

**Comment by alex-swiftify** [comment]
Input:
```
while currFnNdx < maxc {
    // recursive function, self.currFnNdx holds our current processing position
    let currTok = ((fnArray)[currFnNdx] as? NSNumber).intValue
    currFnNdx += 1
    if isFn1Arg(currTok) {
        // ...
        //[big massive ugly code]
        //[further modifies self.currFnNdx]
        // ...
    }
}
```

Converter output:
```
while currFnNdx < maxc {
    // recursive function, self.currFnNdx holds our current processing position
    let currTok = ((fnArray)[currFnNdx] as? NSNumber).intValue
    currFnNdx += 1
    if isFn1Arg(currTok) {
        // ...
        //[big massive ugly code]
        //[further modifies self.currFnNdx]
        // ...
    }
}
```
