### ISSUE TITLE
Redundant type annotation for immediately initialised variable

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#29]
There is no need to explicitly annotate a variable with its type when it is immediately initialised.
http://swiftify.me/lh2odh

**Comment by alex-swiftify** [comment]
Fixed, will be available since the next update.

Output:
```
class Asd: NSObject {
    override var description: String {
        for key in ["asd"] {
            print("\(key)")
        }
    }
}
```
