### ISSUE TITLE
[NSURL getResourceValue:forKey:error:]

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#31]
It should be converted to `(try? url.resourceValues(forKeys: [.volumeURLKey]))?.volume`.
http://swiftify.me/7gfww6/1

**Comment by alex-swiftify** [comment]
Resorted to calling the method of NSURL, otherwise, a translation of method call into assignment breaks complex expressions
Output after the changes:
```
        var volumeURL: URL?
        let URL: URL?
        try? (URL as NSURL?)?.getResourceValue(&volumeURL, forKey: .volumeURLKey)
}
```

**Comment by alex-swiftify** [comment]
The only remaining thing to do is taking care of passing an `volumeURL` argument of type `URL?` as an input argument for the `getResourceValue:forKey:` method which requires `Any?` as an input.

**Suggested solution:** (Scheduled for later - https://swiftify.atlassian.net/browse/SWC-875):
1) create a temporary variable (`volumeURLInput`) to be passed as an input parameter;
2) after calling the method, assign the value of the temporary variable to the original variable (`volumeURL`), casting the type as necessary.

The result should look like the following:
{code}
        var volumeURL: URL?
        let URL: URL? = nil
        var volumeURLInput: AnyObject?
        try? (URL as NSURL?)?.getResourceValue(&volumeURLInput, forKey: .volumeURLKey)
        volumeURL = volumeURLInput as? URL
{code}
