### ISSUE TITLE
If added out of nowhere

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#32]
When using an NS_ENUM with NSInteger, calling a method with that enum as an argument is wrapped in an if branch.
http://swiftify.me/6szxag
http://swiftify.me/6szxag/1

**Comment by alex-swiftify** [comment]
Here is "why" we need an `if let` here:
1) The enum `Asd` has no default value, but Swift requires the instance variable `asd` to have an initializer.
Previously, we have resorted to use something like
```
var asd = Asd(rawValue: 0)
```
as the default initializer, but this caused other side effects.
In your particular sample, the enum `Asd` has no value that corresponds to the integer value of 0.

Thus, our current approach is to treat unassigned enum values as optional:
```
    var asd: Asd?
```

2) Since we have declared `asd` as optional, we need an `if let` statement to unwrap it:
```
    if let asd = asd {
        setAsd(asd)
    }
```

The result compiles in Xcode:
https://take.ms/58sJJ

3) Even if we add an initializer to the `asd` variable in Objective-C as follows: http://swiftify.me/6szxag/2
the initializer `Asd(rawValue: 1)` still returns an optional, and thus needs to be unwrapped:
https://take.ms/mM5xd

@nickasd If you can suggest a better "generic case" translation, you are welcome to contribute one and reopen this.

**Comment by nickasd** [comment]
I understand the problem, but wrapping a function inside an if which was not there before changes the program's behaviour. Once the converter will be able to infer that the enum is initialised on all branches and hence is not an optional, this will not be a problem anymore, but in the case that the enum is not initialised on all branches I would still prefer `var asd = Asd(rawValue: 0)`, or maybe even better call the function like this: `setAsd(asd) ?? .qwe)`.

**Comment by alex-swiftify** [comment]
>Once the converter will be able to infer that the enum is initialised on all branches and hence is not optional, this will not be a problem anymore

Understandable, but 
(1) it's very difficult to infer that (logged this in another issue anyway), and 
(2) we still have to cover the case when the enum is not initialized.

As I recall, the major problem we had with using `(rawValue: 0)` as the default initializer was that there are non-int based enums.

For example, if we had [Calendar.Identifier](https://developer.apple.com/documentation/foundation/calendar/identifier) in place of the `Asd` enum, either of 
* `Calendar.Identifier(rawValue: 0)` (which just won't compile: https://take.ms/RHVtu)
or 
* `setCalendarIdentifier(calendarIdentifier ?? .buddhist)` (since `.buddhist` is the first declared enum value)
seems problematic to me, and using an optional `Calendar.Identifier?` does not alter the program flow that much.

Hence the approach with using non-optional enums initialized with a default value resulted in an increased error rate within the projects we tested with.

So once again, if you see a generic case solution that will fit all cases, you are welcome to contribute.
Otherwise, the best way I can see we could handle this adding a configurable option to initialize enums with a default value instead of using optionals.

**Comment by alex-swiftify** [comment]
JIRA issue: SWC-873 Add a configurable option to initialize enums with the default value (instead of declaring them as optional).

**Comment by nickasd** [comment]
I don't think such an option is necessary (for me at least).
It sounds like you want to avoid compiler errors at all costs, but personally I would feel safer going over a compile error than knowing that the program's behaviour changed.

> and using an optional Calendar.Identifier? does not alter the program flow that much.

I agree, but again, optionally calling a method does alter the program flow, and I think it should rather result in a compile error than a changed program behaviour. Knowing that this issue exists, I always have to check that all `if`s also occur in the original code, while if I simply encounter a compile error I know that I either missed to initialize the enum on all branches, or I can change its declaration to a non-optional so that the compile error goes away.

**Comment by alex-swiftify** [comment]
So, what’s your suggestion?
Leave the enum declaration uninitialized and non-optional, instead of initializing it with a default value?

**Comment by nickasd** [comment]
Well, I would go with a non-optional enum. Can Objective-C enums even be `nil`? I'm not an expert but I don't think so, in which case I would definitely leave the enums as non-optionals; in the rare case that the programmer forgot to initialize it on all branches, he would get a compile error which would allow him to correct the program.
What I would avoid at all costs is changing the program behaviour by adding or removing branches.

**Comment by alex-swiftify** [comment]
@nickasd, Unlike Objective-C, Swift requires any enum field or variable to have an initializer.
While decreasing the error rate is not the only goal, it's still the most important measure that we use to evaluate the impact of our converter changes.

My suggestion was to include an option that will judge whether:
1) we declare the enum as optional (results in a lower error rate, but changes the flow as you mentioned);
2) declare the enum as non-optional, but add a default initializer (i.e. `Asd(rawValue: 0)`) - this matches the Objective-C behavior, but such a default initializer is available not for all enums;
3) declare the enum as non-optional, and don't generate any initializer.

In my opinion, making it possible to switch between (1) and (2) will be sufficient,
but if you strongly vote for an option to make (3) possible, let me know.

**Comment by nickasd** [comment]
My point is that if a developer initialized an enum on all branches in Objective-C, then it would translate to valid Swift even when the converter would declare the enum as non-optional and not initialize it on declaration. For example like this:
```
enum Asd {
    let asd1
    let asd2
}

let asd: Asd
if (boolean) {
    asd = .asd1
} else {
    asd = .asd2
}
```
If the developer didn't initialize the enum on all branches, then it probably is an error (since it cannot be `null`), don't you think? In this case, without the converter initializing the enum on declaration, the programmer would notice the error and correct it.

> Unlike Objective-C, Swift requires any enum field or variable to have an initializer.

When the enum is an instance variable of class A, then it should be initialized in A's initializer or, if it has no initializer (like for example when subclassing `NSView` and initializing instance variables in `awakeFromNib`), it can be declared as an (ideally implicitly unwrapped) optional. If the developer doesn't initialized the enum this way, then again it probably is an error, don't you think?

Summarizing: an enum cannot be `null` in Objective-C so it should be translated to a non-optional unless it is an instance variable of a class without initializers.

> While decreasing the error rate is not the only goal, it's still the most important measure

You mean compiler errors, not runtime errors (or problems), right? Well, I disagree. It will be far easier to correct a compiler error than figuring out why the program does not behave the same way as before the conversion because an if was added only to avoid generating a compiler error. It seems like your philosophy is to generate the cleanest looking possible output, but I think many would prefer knowing that that their program behaves the same as before.

**Comment by alex-swiftify** [comment]
>When the enum is an instance variable of class A, then it should be initialized in A's initializer
In exactly this case, we cannot declare the enum instance variable as non-optional in Swift if it is initialized later in the code.

We can use either of
```
var asd: Asd?
```
or 
```
var asd: Asd!
```
At an earlier stage, we were generating implicitly unwrapped optionals (`!`) in such case, but we were blamed a lot about that.

So, if we want a "third" option to omit optionals and omit an initializer, we have to declare `asd` instance variable as implicitly unwrapped (which is indeed the closest to Objective-C behavior, but same time not something that you will want the final code to look like).

>You mean compiler errors, not runtime errors (or problems), right? Well, I disagree. 
Your points are understandable.
The number of compiler errors is still the most reliable metric that we can automatically retrieve after each project conversion. I agree that this is not the only goal, but (for instance) we cannot automate measuring the number of runtime errors so far.

**Comment by nickasd** [comment]
> At an earlier stage, we were generating implicitly unwrapped optionals (!) in such case, but we were blamed a lot about that.

Well, I don't see what's wrong with that since Objective-C doesn't allow an enum to be null, so I would go for implicitly inwrapped optionals when the enum is an instance variable initialized late, but when it is not an instance variable like in my original example it should be a non-optional in my opinion.

To be honest, this enum story is not as important to me as is to maintain the same program behaviour. I was just surprised about this new if that was added by the converter, which as you already know I think is quite dangerous, because if the developer doesn't notice it he could spend quite some time debugging the new code, and perhaps he doesn't even notice and ships the app to his customers which then have a bad surprise. Of course you want to generate compile error free code whenever possible, but when this is not possible without changing program behaviour, the compile error is just a sign that the developer should review his code. To me this is clearly something to be corrected, but if you don't see it this way, I don't know what else to say.

**Comment by alex-swiftify** [comment]
Your points are understandable.
We will consider adding a configurable option to either
(a) add a default initializer, or
(b) declare an enum as non-optional.

**Comment by alex-swiftify** [comment]
@nickasd I have finally revisited this and addressed very close to your suggestions:
- Use non-optional enum type for local variables, protocol properties, struct or union fields;
- Use Implicitly Unwrapped Optional (`!`) enum type for class properties and global variables.

After the next update, [your sample](http://swiftify.me/6szxag) will output the following:
```
enum Asd : Int {
    case qwe = 1
}

func setAsd(_ asd: Asd) {
}

func bla() {
    var asd: Asd
    if boolean {
        asd = .qwe
    }
    setAsd(asd)
}
```


Question: are you fine with using `!` for both backing fields and properties in the above sample?
I could not find anything better than below to keep the behavior consistent.

**Input**:
```
@interface Test
@property (nonatomic) UIInterfaceOrientation interfaceOrientation;
@end
@implementation Test
- (void)setInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation {
    if (interfaceOrientation != _interfaceOrientation) {
        _interfaceOrientation = interfaceOrientation;
    }
}
@end
```

**Output**:
```
class Test {
    private var _interfaceOrientation: UIInterfaceOrientation!
    var interfaceOrientation: UIInterfaceOrientation! {
        get {
            return _interfaceOrientation
        }
        set(interfaceOrientation) {
            if interfaceOrientation != _interfaceOrientation {
                _interfaceOrientation = interfaceOrientation
            }
        }
    }
}
```

**Comment by nickasd** [comment]
That's good to hear, thanks.
Why do you think there would be a problem with nonatomic properties? I didn't think about this case, but I don't see why it should be different.

**Comment by alex-swiftify** [comment]
@nickasd, you are always welcome :)

1) In my mind, the backing field should have been initialized with a default value, so I was thinking if using an optional (`?`) for a backing field will be better.
2) Xcode imports such an enum property declaration as non-optional, and so is the declaration of `interfaceOrientation` in the Apple Help
https://developer.apple.com/documentation/uikit/uiviewcontroller/1621373-interfaceorientation
So, another option was using non-optional for the property type.

So, the alternatives considered were as follows (but I could not gather enough votes for any of them):

1) 
```
class Test {
    private var _interfaceOrientation: UIInterfaceOrientation?
    var interfaceOrientation: UIInterfaceOrientation! {
        get {
            // Drawback: we have to unwrap using `??` operator or otherwise use `!` which will fail with the initial `nil` value
            return _interfaceOrientation ?? .unknown
        }
        set(interfaceOrientation) {
            if interfaceOrientation != _interfaceOrientation {
                _interfaceOrientation = interfaceOrientation
            }
        }
    }
}
```

2)
```
class Test {
    private var _interfaceOrientation: UIInterfaceOrientation!
    var interfaceOrientation: UIInterfaceOrientation {
        get {
            // Same as in the previous sample, we still have to explicitly unwrap the IUO value to avoid it being implicitly unwrapped and producing a crash
            return _interfaceOrientation ?? .unknown
        }
        set(interfaceOrientation) {
            if interfaceOrientation != _interfaceOrientation {
                _interfaceOrientation = interfaceOrientation
            }
        }
    }
}
```

**Comment by nickasd** [comment]
I don't know what you mean when you say that "Xcode imports" something ... But looking at it quickly, your previous fix looks good to me.

**Comment by alex-swiftify** [comment]
@nickasd I mean the Xcode's "Generated Interface" feature that allows converting an Objective-C header (without implementation) to Swift: MyInterfaceOrientation
![image](https://user-images.githubusercontent.com/3234792/58627100-10a3d100-82df-11e9-9cad-0d0d1d9cef0a.png)

**Comment by nickasd** [comment]
So Xcode converts a nonatomic property to a non-optional. Personally I'm not too picky about whether it should be a non-optional or implicitly unwrapped optional (even though a non-optional would probably be the best solution), but since you have all the necessary background to assess this, I leave it up to you.
