### ISSUE TITLE
For loop variable is declared as optional

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#36]
Since `NSArray` cannot contain `nil`, it is unnecessary to use `Any?`.
http://swiftify.me/pb0jae

**Comment by alex-swiftify** [comment]
Fixed, will be available since the next update.

Output:
```
        for obj in [] {
        }
```

**Comment by alex-swiftify** [comment]
Update: added back explicit type name in if the r-value is an empty collection literal (`[]` or `[:]`):
```
for obj: Any in [] {
}
```
