### ISSUE TITLE
Can see anything in dark mode in Offline Converter

### ISSUE THREAD

**Issue by appfrilans** [Swiftify-Corp/Swiftify#4]
With newest macOS in dark mode you cannot use the app because you cannot see anything. This after opening a projekt.

**Comment by alex-swiftify** [comment]
Hey @jonasecandersson, thanks for the report - excited that you are using the Dark Mode in Mojave!

We will address this ASAP. You will get an updated Offline version once available via automatic updates.

Note that the current version of the Offline Converter if the last one with support for Swift 4.1.
A new version of the Offline Converter (which is about to be released) will support Swift 4.2, and we will ensure that this fix will be also included.

**Comment by alex-swiftify** [comment]
@jonasecandersson, we have just released updated versions of both the Offline Converter and Swiftify for Xcode with full support for the Dark Mode in macOS Mojave. 

Thanks again for reporting!
