### ISSUE TITLE
[NSFileManager createDirectoryAtURL:withIntermediateDirectories:attributes:error:]

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#42]
This method has no return type in Swift.
http://swiftify.me/vk2y0e

**Comment by alex-swiftify** [comment]
JIRA issue: SWC-173 Ignore return value for a method returning NSError (wrapped into try statement).

**Comment by alex-swiftify** [comment]
@nickasd The best way I see we could handle this is as follows:
```
var success = true

do {
    try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true, attributes: nil)
}
catch {
    success = false
}
```

let me know if you have better suggestions.

**Comment by nickasd** [comment]
This looks good. If the `error` parameter is omitted, you could do `let success = try? try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true, attributes: nil)`.

**Comment by alex-swiftify** [comment]
@nickasd While working on this, I found that with your suggested `try?` statement,
the `success` variable has a type `()?`: https://take.ms/M3Ady
(which is useless for anything other than comparing with `nil`).

Thus I'd probably won't use a `try?` approach with this particular method in production,
and resort to the common case (a `try` statement wrapped into `do..catch` block as suggested above).

**Comment by alex-swiftify** [comment]
Done (will be included in the next update).

Actual output after the changes:
```
        var success: Bool = false
        do {
            try FileManager.default().createDirectory(at: url, withIntermediateDirectories: true, attributes: nil)
            success = true
        } catch {
        }
```
