### ISSUE TITLE
[NSString cStringUsingEncoding:]

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#44]
`String.Encoding.utf8.rawValue` should really be `.utf8`.
http://swiftify.me/hq6lc7

**Comment by tomattoz** [comment]
Type like "const char *" should be converted to UnsafePointer<...>, in this case UnsafePointer<Int8>, because char translates to Int8. 
Also "const" here doesn't mean UnsafePointer should be "let", actually looks like we can just skip "const" for pointer types while translation.

**Comment by tomattoz** [comment]
Now it produces next result:
`(string as NSString).cString(using: String.Encoding.utf8.rawValue)`

Which compiles successfully.
