### ISSUE TITLE
Ternary operator with [NSObject isKindOfClass:]

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#45]
Objective-C: `[_object isKindOfClass:[NSRegularExpression class]] ? ((NSRegularExpression *)_object).pattern : _object);`.
Converted to: `(object is NSRegularExpression) ? (object as? NSRegularExpression)?.pattern : object`.
Should be: `(object as? NSRegularExpression)?.pattern ?? object`.
http://swiftify.me/vhnmvq

**Comment by alex-swiftify** [comment]
This seems to duplicate https://github.com/Swiftify-Corp/Swiftify/issues/13 - will leave that one open.
