### ISSUE TITLE
[NSControl objectValue] and [NSControl setObjectValue]

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#46]
It results in a double generation of a `var objectValue`, one for the getter and one for the setter.
http://swiftify.me/7q8505/1

**Comment by tomattoz** [comment]
Issue: https://swiftify.atlassian.net/browse/SWC-1044

**Comment by alex-swiftify** [comment]
@nickasd  Fixed (will be available in the next update).

Converter output:
```
class Asd: NSControl {
    override var objectValue: Any? {
        get {
            return nil
        }
        set(objectValue) {

        }
    }
}
```
