### ISSUE TITLE
NSRect by {NSPoint, NSSize}

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#47]
This is a valid syntax in Objective-C, but it is translated to `[point, size]` which gives an array in Swift.
http://swiftify.me/sv9bxn

**Comment by tomattoz** [comment]
Looks like it's already fixed.
NSRect rect={NSZeroPoint, NSZeroSize};
->
let rect = NSRect(NSPoint.zero, NSSize.zero)
