### ISSUE TITLE
[NSControl cellClass] is converted to getter only

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#49]
It is translated to `override class var cellClass: AnyClass?` with only a getter, which generates the error `Cannot override mutable property with read-only property 'cellClass'`.
http://swiftify.me/m1x304/1

**Comment by tomattoz** [comment]
Issue: https://swiftify.atlassian.net/browse/SWC-1045

**Comment by alex-swiftify** [comment]
Fixed (will be available in the next converter update).

Converter output:
```
class Asd: NSControl {
    override class var cellClass: AnyClass? {
        get {
            return Asd.self
        }
        set(newValue) {
            super.cellClass = newValue
        }
    }
}
```
