### ISSUE TITLE
NSMutableIndexSet declared as var

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#51]
`let` is sufficient.
http://swiftify.me/uvbb0h

**Comment by tomattoz** [comment]
Issue: https://swiftify.atlassian.net/browse/SWC-1046

**Comment by alex-swiftify** [comment]
Fixed (will be available since the next update).
Converter output:
```
let allowedSet = CharacterSet.letters
allowedSet.insert(charactersIn: " ")
```
