### ISSUE TITLE
[NSControl validateMenuItem:]

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#53]
This method doesn't exist anymore, one should probably use `NSControl.validateUserInterfaceItem()`.
http://swiftify.me/16xpg8

**Comment by tomattoz** [comment]
As I understand swift versions is the same, but just moved to protocol NSMenuItemValidation:
https://developer.apple.com/documentation/appkit/nsmenuitemvalidation/3005191-validatemenuitem
