### ISSUE TITLE
Accessing @property with underscore _ variable

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#55]
The generated instance variable with the `_` prefix is not available in Swift.
http://swiftify.me/tf78te

**Comment by alex-swiftify** [comment]
This seems to be a capitalization issue.
Works with lowercase identifiers i.e. http://swiftify.me/tf78te/2

**Comment by nickasd** [comment]
Currently I cannot check it because I have exceeded the number of daily conversions checking some other issues, but I think the identifier used in my example is already lowercase.

**Comment by tomattoz** [comment]
@alex-swiftify please take a look at this. I'm not so familiar with code the problem is with.

**Comment by alex-swiftify** [comment]
Fixed. Converter output:
```
class Asd: NSObject {
    var url: URL?

    func asd() {
        url = nil
    }
}
```
