### ISSUE TITLE
Using contextual type in various methods that accept an options argument

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#56]
Instead of writing
`pasteboard?.canReadObject(forClasses: [URL.self], options: [NSPasteboard.ReadingOptionKey.urlReadingFileURLsOnly: NSNumber(value: true), NSPasteboard.ReadingOptionKey.urlReadingContentsConformToTypes: [kUTTypeDirectory as String]])`
it would suffice
`pasteboard?.canReadObject(forClasses: [URL.self], options: [.urlReadingFileURLsOnly: NSNumber(value: true), .urlReadingContentsConformToTypes: [kUTTypeDirectory as String]])`
http://swiftify.me/n97474

**Comment by tomattoz** [comment]
The same as in https://github.com/Swiftify-Corp/Swiftify/issues/58 (https://swiftify.atlassian.net/browse/SWC-1047)

**Comment by alex-swiftify** [comment]
Fixed. Converter output:
```
let pasteboard: NSPasteboard? = nil

pasteboard?.canReadObject(forClasses: [NSURL.self], options: [
    .urlReadingFileURLsOnly: NSNumber(value: true),
    .urlReadingContentsConformToTypes: [kUTTypeDirectory as String]
])
```
