### ISSUE TITLE
Not all methods for classes without the NS prefix are ported

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#57]
For example `[NSURL URLFromPasteboard:]` is not available on `URL` but only on `NSURL`.
http://swiftify.me/s6t1a7

**Comment by alex-swiftify** [comment]
This is a huge task being in progress for months.
We do plan to completely cover translations for most used Framework classes like NSString/Array/Dictionary/Set/NSURL/etc in the nearest time.
JIRA issue: https://swiftify.atlassian.net/browse/SWC-128

**Comment by alex-swiftify** [comment]
@nickasd NSURL class methods have now been ported: https://swiftify.atlassian.net/browse/SWC-128

Few more classes will be ported as parts of these tasks:

- https://swiftify.atlassian.net/browse/SWC-128
- https://swiftify.atlassian.net/browse/SWC-540
