### ISSUE TITLE
Typing is very slow

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#61]
When typing, each letter takes around 1 second to appear.
https://objectivec2swift.com/#/converter/

**Comment by alex-swiftify** [comment]
JIRA issue: https://swiftify.atlassian.net/browse/SWF-1099

**Comment by alex-swiftify** [comment]
@nickasd Are you using Safari? Do you see that same behavior in other browsers?

**Comment by nickasd** [comment]
I'm on Safari and you're right, it doesn't happen with other browsers.

**Comment by alex-swiftify** [comment]
@nickasd Does this still happen?
I see no problems with the latest Safari on Catalina: https://share.getcloudapp.com/DOuGxYqe

**Comment by nickasd** [comment]
For me it's still quite slow.

**Comment by alex-swiftify** [comment]
@nickasd Does that happen to you on macOS Catalina (10.15)?

**Comment by nickasd** [comment]
Yes, macOS 10.15. Safari takes half a second for each character to appear, and Firefox is fast as it should be.
