### ISSUE TITLE
[NSOutlineView selectRowIndexes:byExtendingSelection:]

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#62]
The generated code passes an `NSMutableIndexSet` where an `IndexSet` is expected, generating the error `'NSMutableIndexSet' is not implicitly convertible to 'IndexSet'; did you mean to use 'as' to explicitly convert?`.
http://swiftify.me/4j28az

**Comment by tomattoz** [comment]
Done.
