### ISSUE TITLE
Return type is optional despite returning non-optional

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#65]
http://swiftify.me/shr0vz

**Comment by nickasd** [comment]
I personally don't get the need for an implicitly unwrapped parameter or return type, but apart from that, I can just say that I had no `__nonnull` annotations in my Objective-C code, so I would have appreciated if the converter would have done it for me. In the end, if a function returns a non-null type, why should it be declared as optional? But I leave it up to you.

**Comment by alex-swiftify** [comment]
@nickasd 

> In the end, if a function returns a non-null type, why should it be declared as optional?

Imagine that the `popoverForView:` method is yet in Objective-C, but the class using this method has been converted to Swift.
As I demonstrated above, Xcode would import this method as follows:
```
func popover(for view: NSView!) -> NSPopover!
```

The calling code would need to use the `?` operator when accessing properties of `NSPopover`.
Here is a quick mock to demonstrate that:
```
import Foundation

class MyClass {
    func popover(for view: NSView!) -> NSPopover! {
        return nil
    }
}

class NSView {
}

class NSPopover {
    var text: String = ""
}

var view: NSView!

MyClass().popover(for: view)?.text // the results shoud be accessed with `?` operator
```

Now consider we have converted `MyClass` to Swift.
If we have changed the return type to non-optional (`NSPopover`) the code using `MyClass` will break after this conversion.


P.S. In Swiftify, we use `?` as the default optional specifier for pointer declarations (but [this behavior is now configurable](https://support.swiftify.com/hc/en-us/articles/360030931171-Optional-specifier-to-be-used-for-pointer-type-method-parameters-and-return-types)):
```
func popover(for view: NSView?) -> NSPopover?
```

**Comment by nickasd** [comment]
I didn't try to understand what Xcode does when importing Objective-C header files to Swift, but I understand that you want to keep compatibility. I personally converted the whole project to Swift, so using a non-optional return type would have been just fine.
I think I saw in another ticket that there is an option to always assume return types to be non-optional. If that's the case, then this would probably solve my problem. Otherwise, an option to automatically infer the return type (optional or not) would also be welcome.

**Comment by alex-swiftify** [comment]
>I think I saw in another ticket that there is an option to always assume return types to be non-optional. If that's the case, then this would probably solve my problem.

That's it. Agreed.
Additionally, you may use nullability annotations in Objective-C (supported by our converter) to handle individual cases.

I see some issues with automatically inferring the return type at the current stage.
We may consider this for later, but for now, you have configurable options and nullability annotations.
