### ISSUE TITLE
Website reports that nothing has been converted yet

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#68]
Even though I have converted plenty of code by now.

<img width="653" alt="Bildschirmfoto 2019-03-16 um 17 43 14" src="https://user-images.githubusercontent.com/26737509/54478490-fe071900-4812-11e9-872d-9b2fe0538473.png">

**Comment by alex-swiftify** [comment]
JIRA issue: https://swiftify.atlassian.net/browse/SWF-1122

**Comment by alex-swiftify** [comment]
@nickasd This issue should have been fixed on our website around March, 5th.

Can you confirm that if you log in to your account (`nicolas.kick@gmail.com`) and perform one or few (free) online conversions, you still see 0's in your profile?

Thanks in advance!

**Comment by nickasd** [comment]
<img width="565" alt="Bildschirmfoto 2019-04-03 um 14 54 39" src="https://user-images.githubusercontent.com/26737509/55480361-6b42e880-5620-11e9-8ce3-775d2b017d77.png">
Now it seems to show something. Although I'm not sure what "Pay per use" means: will my credit card be charged automatically?

**Comment by alex-swiftify** [comment]
The [Pay As You Go](https://objectivec2swift.com/#/pricing/pay-as-you-go) plan is essentially a free plan but allows paying for an individual project conversion at the [Converter -> Project](https://objectivec2swift.com/#/converter/project/) page: https://take.ms/x6vFjm

You never get charged automatically unless you select any of our [subscription plans](https://objectivec2swift.com/#/pricing/subscription/).

Hope this helps. Thanks for the confirmation!

**Comment by nickasd** [comment]
Ok. You may want to rephrase "Daily conversions" to "Daily free conversions" to make that clearer.

**Comment by alex-swiftify** [comment]
@nickasd Thanks for the suggestion!
Agreed - we will change that.
