### ISSUE TITLE
Casting and sorting array at the same time

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#71]
Results in error `Cannot assign to immutable expression of type '[AnyHashable]?'`.
http://swiftify.me/x77rud

**Comment by tomattoz** [comment]
We should translate casts to mutable type (like "(NSMutableArray *) asd)") as changing let to var in variable declaration. 

So for declarations:

"let asd; ... (NSMutableArray *) asd) ..."
 ->
"var asd; ... asd ..."

If it is function parameter:  
"func foo (asd: [String]) ... (NSMutableArray *) asd) ..." 
-> 
"func foo (asd: inout [String]) ... asd ..."

**Comment by alex-swiftify** [comment]
Fixed (will be available in the next update).
Converter output:
```
var asd: [AnyHashable]?
asd = (asd as NSArray?)?.sortedArray(comparator: { _,_ in return ComparisonResult.orderedSame }) as? [AnyHashable] ?? asd
```
