### ISSUE TITLE
NSLocalizedString doesn't support string interpolation

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#78]
Format parameters like `%@` should be preserved.
http://swiftify.me/5lkw94

**Comment by tomattoz** [comment]
Task: https://swiftify.atlassian.net/browse/SWC-1049

**Comment by alex-swiftify** [comment]
Fixed (will be available since the next update).
Converter output:
```
let bla: String? = nil
String.localizedStringWithFormat(NSLocalizedString("asd %@", comment: ""), bla ?? "")
```
