### ISSUE TITLE
Immediately assigned variable has type declaration

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#79]
Type declaration is not necessary in Swift when the variable is immediately assigned.
http://swiftify.me/u30y1v

**Comment by nickasd** [comment]
The ticket seems to address the same issue, yes, but I still get explicit type declarations for my sample link.

**Comment by alex-swiftify** [comment]
@nickasd Here is what I get at the output for http://swiftify.me/u30y1v
```
let alert: NSAlert? = nil
let response = alert?.runModal()
```
I assume you wanted the declaration of the `response` variable to be implicit (as it is now).
Am I missing anything?

**Comment by nickasd** [comment]
Sorry, yes, that's probably what I wanted. I saw the `alert` still having an explicit type but that's needed in this case since it's initialized to `nil`.
