### ISSUE TITLE
[CIFilter filterWithName:keysAndValues:]

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#8]
`[[CIFilter filterWithName:@"CIColorInvert" keysAndValues:kCIInputImageKey,image,nil] outputImage]` should be converted to `CIFilter(name: "CIColorInvert", parameters: [kCIInputImageKey: image])?.outputImage`.
http://swiftify.me/vcvgrz

**Comment by alex-swiftify** [comment]
Fixed.

Input:
```
[[CIFilter filterWithName:@"CIColorInvert" keysAndValues:kCIInputImageKey,image,nil] outputImage];
```

Output:
```
CIFilter(name: "CIColorInvert", parameters: [kCIInputImageKey : image])?.outputImage
```
