### ISSUE TITLE
Assignment inside if statement which is used in a following expression in the same if

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#81]
Objective-C:
```
NSData *data;
(data=[NSData data])==nil || [NSData dataWithData:data]==nil;
```
Converted Swift:
```
var data: Data?
if let data = data {
    (data = Data()) == nil || Data(data: data) == nil
}
```
Expected Swift:
```
var data: Data?
(data = Data()) == nil || Data(data: data!) == nil
```
http://swiftify.me/j6dfcx/1

**Comment by tomattoz** [comment]
"Expected Swift:" is not equal to "Objective-C:". In case of data == nil code "Data(data: data!)" crash app, but [NSData dataWithData:data] silently return zero length data.

So unfortunately we can't precisely convert this code to swift, only manually.

**Comment by nickasd** [comment]
Not only is `(data = Data()) == nil || Data(data: data) == nil` never executed because inside of an `if` that is always `false`, but what I actually wanted to point out is that when `Data(data: data!)` is executed `data` will always be nonnil since otherwise the boolean expression would have been short-circuited (due to `(data = Data()) == nil`).

**Comment by tomattoz** [comment]
Yeah, I understand your point :-) Suggested by you conversion result is right.

In general we couldn't unwrap with "!". Why? You can take a look at this example ))

In this case converter couldn't make conversion right way without making logical operations. But it's not a task of converter. It is the main reason. So the best thing converter can do is to produce a code with compilation error. From this point the current result is right (for converter). For user: he will see error and can do things right ...

So I still think that current result is right for converter.
