### ISSUE TITLE
Assigning instance variable to itself

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#85]
Currently results in commented out code with the comment `// Skipping redundant initializing to itself`, but the getter and/or setter for that instance variable might have side effects that are not executed anymore.
http://swiftify.me/qdz6qe

**Comment by alex-swiftify** [comment]
@nickasd This was already discussed in #95.
Are you okay with the below behavior, or do you suggest that we rather always keep such assignments uncommented?

To brief:

1. The assignment expression is commented out only if the l-value exactly matches the r-value.
For example, `self.asd=self.asd;` will be commented out but not `self.asd=asd;`

2. The converter has a logic to skip (redundant) `self.` prefixes.
However, `self.` prefix will be kept if there is an existing instance varaible, parameter or a property declaration with the same name. 
A related case (#26) has been fixed.

3. A (pretty exotic) case why we need to skip the redundant initializer is mentioned in https://github.com/Swiftify-Corp/Swiftify/issues/95#issuecomment-479397745

**Comment by nickasd** [comment]
I think the redundant initializer to itself can be skipped if the lvalue is a local variable, but it should not be skipped if it is an instance variable, since the setter can have side effects.

**Comment by arlomedia** [comment]
I've run into this, too, and agree with @nickasd that this should be allowed with instance variables. However, the current Swift compiler marks "Assigning a property to itself" as an error and won't build with it. I still think it's best for Swiftify to leave this code as-is since it's better to get a compiler error than to get a sneaky new bug.

FWIW, I've been using the solution of moving setter code to a separate function that I can call directly, as illustrated here: https://stackoverflow.com/a/43072479/462162

**Comment by alex-swiftify** [comment]
@arlomedia After reading the previous underlying issues here is the objective "why" do we skip redundant initialization of variables to itself.
There are cases when the original Objective-C code was **not exactly** an assignment to itself, but the resulting Swift code contains such an assignment:
`attributes = [attributes mutableCopy]; `
translates to 
`attributes = attributes`.

This case looks pretty exotic but demonstrates one of the cases why we originally decided to skip such initializers:
https://github.com/Swiftify-Corp/Swiftify/issues/95#issuecomment-479397745

What do you think of such a solution?
```
#warning("Swiftify: Skipping redundant initializing to itself")
//asd = asd
```

This requires minimum efforts to change and test and will produce a warning in Xcode: https://take.ms/sWzuy

**Comment by arlomedia** [comment]
Sure, that seems like a good compromise.

**Comment by alex-swiftify** [comment]
Fixed (will be available in the next update).

Input:
```
- (void)test:(NSDictionary *)attributes {
    attributes=[attributes mutableCopy];
}
```

Converter output:
```
func test(_ attributes: [AnyHashable : Any]?) {
    var attributes = attributes
    #warning("Swiftify: Skipping redundant initializing to itself")
    //attributes = attributes
}
```
