### ISSUE TITLE
IBAction parameters always declared as non-optional

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#87]
While other `func`s parameters are always declared as optional.
http://swiftify.me/8n2b6q/1

**Comment by alex-swiftify** [comment]
@nickasd The rationale for this was that Xcode generates non-optional `sender` and `event` parameters when creating an `@IBAction` method using IB: 
https://take.ms/q8fCS

Same time, Xcode imports your Objective-C method with optional parameters:
https://take.ms/IK0o5

I am thinking about changing only `sender` and `event` parameters for IBAction methods to non-optional. 
What do you suggest?
Interesting to see your real-world sample `@IBAction` method which parameters should be optional.

**Comment by nickasd** [comment]
Ok, probably it's better to do what Xcode does by default.

**Comment by alex-swiftify** [comment]
P.S. For now, implemented as suggested.
Converter output:
```
class Asd: NSObject {
    @IBAction func asd(_ a: Any?, b: String?, c: [Any]?) {
    }

    func bla(_ a: Any?, b: String?, c: [Any]?) {
    }
}
```

Sample input with the `sender` parameter:
```
@interface CSICAboutViewController ()<MFMailComposeViewControllerDelegate>
- (IBAction)onEmailButtonTap:(UIButton *)sender;
@end
```

Output:
```
class CSICAboutViewController: MFMailComposeViewControllerDelegate {
    @IBAction private func onEmailButtonTap(_ sender: UIButton) {
    }
}
```
