### ISSUE TITLE
Instance variable and private property result in double property

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#89]
http://swiftify.me/pimssr

**Comment by alex-swiftify** [comment]
@nickasd Before attempting to merge these 2 declarations in the converter, could you explain what was the original intent of this code?

According to the following Xcode's warning below, I assume that there will be a separate field + property with the same name in Objective-C:

> Autosynthesized property 'asd' will use synthesized instance variable '_asd', not existing instance variable 'asd'

https://take.ms/M2uz2

**Comment by nickasd** [comment]
I forgot an underscore, here is the updated version: http://swiftify.me/pimssr/1

**Comment by alex-swiftify** [comment]
Fixed (will be available in the next update).
Converter output:
```
class Asd: NSObject {
    private var asd: Any?
}
```
