### ISSUE TITLE
Feature request to conform properties to Swift semantics for nonnull attribute 

### ISSUE THREAD

**Issue by Ibrahimhass** [Swiftify-Corp/Swiftify#97]
**Original Objective-C input**
```
#import "ViewController.h"

@interface ViewController ()
@property (nonnull, strong, nonatomic) NSString *userName;
@end

@implementation ViewController
- (void)viewDidLoad {
    [super viewDidLoad];
    _userName = @"Swiftify";
    // Do any additional setup after loading the view.
}
```
**Converter Output**
```
import UIKit

class ViewController: UIViewController {
    private var userName: String

    override func viewDidLoad() {
        super.viewDidLoad()
        userName = "Swiftify"
        // Do any additional setup after loading the view.
    }
}
```
**Expected output according to Swift semantics**

```
import UIKit

class ViewController: UIViewController {
    private var userName: String!

    override func viewDidLoad() {
        super.viewDidLoad()
        userName = "Swiftify"
        // Do any additional setup after loading the view.
    }
}
```

**Comment by alex-swiftify** [comment]
@Ibrahimhass 
1) See this link for the default converter output: http://swiftify.me/uhvqyy

You have probably got `private var userName: String` after unchecking the "Initialize properties without initializers with default values of their type" option in the "Swiftify for Xcode" app: https://take.ms/97dbi

2) If you change the type name from String (which we add the default initializer to) to anything else like `MyClass`, the converter correctly emits `!` declaration.

3) I've added the following suggestion to our JIRA to emit `!` when default initializers are turned off:
SWC-895 Use `!` specifier for nonnull properties when AddDefaultInitializers option is unchecked
