### ISSUE TITLE
XCTAssert with variable number of arguments

### ISSUE THREAD

**Issue by nickasd** [Swiftify-Corp/Swiftify#98]
`XCAssert()` in Objective-C used a variable number of arguments for message string formatting, but Swift has just a single message argument after the expression argument.
http://swiftify.me/izd5rd

**Comment by alex-swiftify** [comment]
Fixed (will be available in the next update).
Converter output:
```
assert(true, "\(asd) \(fgh)")
```

**Comment by nickasd** [comment]
Actually, this is not correct. You should keep using `XCTAssert`, because `assert` interrupts the test execution, while `XCTAssert` outputs the error message and goes on with the other tests.
